import {useEffect,useState} from 'react'
import {Alert,Button,Checkbox,Modal,Pagination,Spin} from 'antd'
import type {DeletePlan,DeleteRequest} from '../../shared/types'
export default function DeleteFilesDialog({request,close,finished}:{request:DeleteRequest;close():void;finished(removedJobIds:string[]):void}){
  const [plan,setPlan]=useState<DeletePlan|null>(null),[selected,setSelected]=useState<string[]>([]),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[page,setPage]=useState(1)
  useEffect(()=>{let alive=true;window.framepick.planDelete(request).then(p=>{if(alive){setPlan(p);setSelected(p.files.map(f=>f.id))}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[request])
  async function remove(){if(!plan)return;setBusy(true);setError('');const players=plan.files.some(f=>selected.includes(f.id)&&f.category.includes('视频'))?Array.from(document.querySelectorAll('video')).map(player=>({player,src:player.getAttribute('src')})):[];for(const {player} of players){player.pause();player.removeAttribute('src');player.load()}try{const result=await window.framepick.deleteFiles(plan.token,selected);finished(result.removedJobIds);if(result.errors.length){setError(`已删除 ${result.deleted} 个文件。${result.errors.join('；')}`);setConfirmed(false);setPlan(null);for(const {player,src} of players)if(src){player.src=src;player.load()}}else close()}catch(e){setError((e as Error).message);for(const {player,src} of players)if(src){player.src=src;player.load()}}finally{setBusy(false)}}
  return <Modal open title="删除磁盘文件" width={760} maskClosable={false} onCancel={()=>!busy&&close()} footer={<><Button disabled={busy} onClick={close}>取消</Button><Button danger type="primary" disabled={!plan||!selected.length||!confirmed} loading={busy} onClick={()=>void remove()}>真正删除 {selected.length} 个文件</Button></>}>
    <Alert type="error" showIcon title="这是真正的文件删除，不是清除记录或历史。" description="选中的文件将从当前存放位置移入系统回收站。删除导出图片时同步清理对应备注和记录；全部结果删完后移除任务。删除视频时保留列表记录。只处理下方明确列出的文件，不删除整个文件夹。请特别核对标为“本地原视频”的项目。"/>
    {error&&<Alert type="error" title={error} style={{marginTop:12}}/>}{!plan&&!error?<Spin/>:plan&&<><div className="delete-choice"><Checkbox checked={selected.length===plan.files.length} indeterminate={selected.length>0&&selected.length<plan.files.length} onChange={e=>{setConfirmed(false);setSelected(e.target.checked?plan.files.map(f=>f.id):[])}}>选择全部 {plan.files.length} 个文件</Checkbox><span>总大小 {(plan.files.filter(f=>selected.includes(f.id)).reduce((sum,f)=>sum+f.size,0)/1048576).toFixed(1)} MB</span></div><div className="delete-file-list">{plan.files.slice((page-1)*50,page*50).map(file=><label key={file.id}><Checkbox checked={selected.includes(file.id)} onChange={e=>{setConfirmed(false);setSelected(prev=>e.target.checked?[...prev,file.id]:prev.filter(id=>id!==file.id))}}/><div><strong className={file.category==='本地原视频'?'delete-original':''}>{file.category} · {file.name}</strong><small>{file.path}</small></div><Button size="small" onClick={()=>void window.framepick.revealPath(file.path).catch(e=>setError(e.message))}>所在文件夹</Button></label>)}</div>{plan.files.length>50&&<Pagination current={page} pageSize={50} total={plan.files.length} showSizeChanger={false} onChange={setPage}/>}<Checkbox className="delete-confirm" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}>我已核对以上文件，确认要删除磁盘上的文件</Checkbox></>}
  </Modal>
}
