const { _electron: electron, expect } = require('@playwright/test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { spawnSync } = require('node:child_process')

const root = path.resolve(__dirname, '..')
const artifact = path.join(root, '.test-artifacts', require('../package.json').version, process.env.FRAMEPICK_PACKAGED_EXE ? 'packaged' : 'desktop')
const runId = Date.now().toString()
const data = path.join(artifact, 'run-' + runId)
const videos = path.join(data, '测试视频')
const output = path.join(data, '截图根目录')
const downloadRoot = path.join(data, '用户选择的下载位置')
fs.mkdirSync(videos, { recursive: true })
fs.mkdirSync(output, { recursive: true })
fs.mkdirSync(downloadRoot, { recursive: true })
const first = path.join(videos, '示例视频.mp4')
const second = path.join(videos, '城市·夜景（测试）.mp4')
const makeVideo = spawnSync(path.join(root, '.tools/ffmpeg.exe'), ['-hide_banner', '-loglevel', 'error', '-y', '-f', 'lavfi', '-i', 'testsrc2=duration=3:size=480x270:rate=20', '-c:v', 'libx264', '-threads', '2', '-pix_fmt', 'yuv420p', first], { windowsHide: true, encoding: 'utf8' })
assert.equal(makeVideo.status, 0, makeVideo.stderr)
fs.copyFileSync(first, second)
const executablePath = process.env.FRAMEPICK_PACKAGED_EXE || require('electron')
const args = process.env.FRAMEPICK_PACKAGED_EXE ? ['--hidden'] : [root, '--hidden']
const errors = []
let application

async function launch() {
  const env = { ...process.env, FRAMEPICK_TEST_DATA: path.join(data, 'user-data'), ELECTRON_RENDERER_URL: '' }
  if (process.env.FRAMEPICK_PACKAGED_EXE) env.PATH = `${process.env.SystemRoot}\\System32;${process.env.SystemRoot}`
  application = await electron.launch({ executablePath, args, timeout: 60000, env })
  const page = await application.firstWindow()
  page.setDefaultTimeout(20000)
  page.on('pageerror', error => errors.push(error.message))
  await waitState(page, value => value.health.ready)
  // Respect reduced motion so hidden-window CSS transitions do not wait for a visible compositor.
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.reload()
  await waitState(page, value => value.health.ready)
  return page
}

async function waitState(page, predicate) {
  await expect.poll(async () => predicate(await page.evaluate(() => window.framepick.snapshot())), { timeout: 60000 }).toBe(true)
}

async function screenshot(name) {
  console.log('STAGE ' + name)
  const png = await application.evaluate(async ({ BrowserWindow }) => {
    const contents = BrowserWindow.getAllWindows()[0].webContents
    // Hidden windows need a capture request to refresh their compositor surface.
    for (let attempt = 0; attempt < 4; attempt++) {
      try {
        await contents.capturePage(undefined, { stayHidden: true, stayAwake: true })
        await new Promise(resolve => setTimeout(resolve, 150))
        const image = await contents.capturePage(undefined, { stayHidden: true, stayAwake: true })
        if (!image.isEmpty()) return image.toPNG().toString('base64')
      } catch (error) { if (attempt === 3) throw error }
      await new Promise(resolve => setTimeout(resolve, 400))
    }
    throw new Error('Hidden capture did not produce an image')
  })
  fs.writeFileSync(path.join(artifact, name + '.png'), Buffer.from(png, 'base64'))
}

(async () => {
  try {
    let page = await launch()
    await expect(page.getByText('从一个视频开始', { exact: true })).toBeVisible()
    await screenshot('empty-state')
    await page.getByRole('button', { name: '新建项目', exact: true }).click()
    await page.getByRole('textbox', { name: '项目名称', exact: true }).fill('旅行素材')
    await page.getByRole('button', { name: /^保\s*存$/ }).click()
    await expect(page.getByRole('textbox', { name: '项目名称', exact: true })).not.toBeVisible()
    await application.evaluate(({ dialog }, values) => {
      dialog.showOpenDialog = async (_window, options) => ({ canceled: false, filePaths: options.properties.includes('openDirectory') ? [values.output] : options.properties.includes('multiSelections') ? values.files : [values.files[0]] })
    }, { files: [first, second], output })
    await page.getByRole('button', { name: '添加视频', exact: true }).click()
    await expect(page.locator('.video-row')).toHaveCount(1)
    await page.getByRole('button', { name: '批量添加', exact: true }).click()
    await expect(page.locator('.video-row')).toHaveCount(2)
    await waitState(page, s => s.videos.length === 2 && s.videos.every(v => v.status === 'ready'))
    const library = await page.evaluate(() => window.framepick.snapshot())
    assert(library.videos.every(video => video.projectId === library.projects[0].id))
    await expect(page.getByRole('button', { name: '下载视频', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: '新建项目', exact: true }).click()
    await page.getByRole('textbox', { name: '项目名称', exact: true }).fill('短片参考')
    await page.getByRole('button', { name: /^保\s*存$/ }).click()
    await expect(page.getByRole('textbox', { name: '项目名称', exact: true })).not.toBeVisible()
    await page.getByRole('button', { name: '移动 城市·夜景（测试） 到项目', exact: true }).click()
    await page.getByRole('menuitem', { name: '短片参考', exact: true }).click()
    await waitState(page, s => s.videos[1].projectId === s.projects[1].id)
    await page.getByRole('button', { name: '收起项目 旅行素材', exact: true }).click()
    await expect(page.locator('.video-row')).toHaveCount(1)
    await page.getByRole('button', { name: '展开项目 旅行素材', exact: true }).click()
    await expect(page.locator('.video-row')).toHaveCount(2)
    await page.getByRole('button', { name: '项目菜单 短片参考', exact: true }).click()
    await page.getByRole('menuitem', { name: '重命名', exact: true }).click()
    await page.getByRole('textbox', { name: '项目名称', exact: true }).fill('短片分镜')
    await page.getByRole('button', { name: /^保\s*存$/ }).click()
    await expect(page.getByRole('textbox', { name: '项目名称', exact: true })).not.toBeVisible()
    await page.getByLabel('移动已选视频到项目', { exact: true }).click()
    await page.locator('.ant-select-dropdown:visible').getByText('短片分镜', { exact: true }).click()
    await waitState(page, s => s.videos.every(video => video.projectId === s.projects[1].id))
    await page.getByRole('button', { name: '移动 示例视频 到项目', exact: true }).click()
    await page.getByRole('menuitem', { name: '旅行素材', exact: true }).click()
    await waitState(page, s => s.videos[0].projectId === s.projects[0].id)
    await page.evaluate(async () => {
      const s = await window.framepick.snapshot()
      const temporary = await window.framepick.createProject('临时分类')
      await window.framepick.moveVideos([s.videos[0].id], temporary)
      await window.framepick.removeProject(temporary)
      const removed = await window.framepick.snapshot()
      if (removed.videos[0].projectId || removed.videos.length !== 2) throw new Error('Removing a project must preserve and unclassify its videos')
      await window.framepick.moveVideos([s.videos[0].id], s.projects[0].id)
      await window.framepick.setActiveProject(s.projects[1].id)
    })
    // Move out of a project, then long-press from unclassified into another folder.
    async function dragVideo(id, target, hold = 450) {
      const source = (await page.evaluate(() => window.framepick.snapshot())).videos.find(video => video.id === id).projectId || "__unclassified__"
      const row = page.locator(`[data-drop-project="${source}"] [data-video-id="${id}"] .video-row-content`)
      await expect(row).toBeVisible()
      await row.scrollIntoViewIfNeeded()
      const from = await row.boundingBox()
      const to = await page.locator(`[data-drop-project="${target}"] .project-heading`).boundingBox()
      await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2)
      await page.mouse.down(); await page.waitForTimeout(hold)
      await expect(page.locator('.video-drag-ghost')).toBeVisible()
      await page.mouse.move(to.x + to.width / 2, to.y + to.height / 2, { steps: 12 })
    }
    await page.evaluate(id => window.framepick.moveVideos([id], null), library.videos[0].id)
    await dragVideo(library.videos[0].id, (await page.evaluate(() => window.framepick.snapshot())).projects[1].id)
    await page.mouse.up()
    await waitState(page, s => s.videos[0].projectId === s.projects[1].id)
    await page.getByRole('button', { name: '置顶 城市·夜景（测试）', exact: true }).click()
    await waitState(page, s => !!s.videos[1].pinnedAt)
    await page.getByRole('button', { name: '取消置顶 城市·夜景（测试）', exact: true }).click()
    await waitState(page, s => !s.videos[1].pinnedAt)
    await page.getByRole('button', { name: '置顶 城市·夜景（测试）', exact: true }).click()
    await waitState(page, s => !!s.videos[1].pinnedAt)
    const current = await page.evaluate(() => window.framepick.snapshot())
    await expect.poll(() => page.locator(`[data-project="${current.projects[1].id}"] .video-row`).evaluateAll(rows => rows.map(row => row.dataset.videoId))).toEqual([current.videos[1].id, current.videos[0].id])
    await page.getByRole('button', { name: '项目菜单 短片分镜', exact: true }).click()
    await page.getByRole('menuitem', { name: '置顶项目', exact: true }).click()
    await waitState(page, s => !!s.projects[1].pinnedAt)
    await expect(page.locator('[data-project]').first()).toHaveAttribute('data-project', current.projects[1].id)
    await page.getByRole('textbox', { name: '搜索视频', exact: true }).fill('夜景')
    await expect(page.locator('.video-row')).toHaveCount(1)
    await page.getByRole('textbox', { name: '搜索视频', exact: true }).fill('完全不匹配的视频')
    await expect(page.locator('.video-row')).toHaveCount(0)
    await page.getByRole('textbox', { name: '搜索视频', exact: true }).fill('')
    await page.getByRole('button', { name: '收起项目 旅行素材', exact: true }).click()
    await dragVideo(current.videos[0].id, current.projects[0].id)
    await page.waitForTimeout(750)
    await expect(page.getByRole('button', { name: '收起项目 旅行素材', exact: true })).toBeVisible()
    await page.mouse.up()
    await waitState(page, s => s.videos[0].projectId === s.projects[0].id)
    // The empty unclassified folder remains a usable destination.
    await dragVideo(current.videos[0].id, '__unclassified__')
    await page.mouse.up()
    await waitState(page, s => !s.videos[0].projectId)
    await dragVideo(current.videos[0].id, current.projects[1].id)
    await page.keyboard.press('Escape'); await page.mouse.up()
    await expect(page.locator('.video-drag-ghost')).toHaveCount(0)
    assert(!(await page.evaluate(() => window.framepick.snapshot())).videos[0].projectId)
    await page.waitForTimeout(100)
    await page.locator(`[data-video-id="${current.videos[0].id}"]`).click()
    await expect(page.locator('.video-title-bar h3')).toHaveText('示例视频')
    await page.evaluate(value => window.framepick.moveVideos([value.video], value.project), { video: current.videos[0].id, project: current.projects[0].id })
    await page.getByRole('button', { name: '移除 示例视频', exact: true }).click()
    await expect(page.locator('.ant-modal-confirm-title').filter({ hasText: '移除这个视频？' })).toBeVisible()
    await page.locator('.ant-modal-confirm').getByRole('button', { name: /^取\s*消$/ }).click()
    assert.equal((await page.evaluate(() => window.framepick.snapshot())).videos.length, 2)
    await page.getByRole('button', { name: '项目菜单 短片分镜', exact: true }).click()
    await page.getByRole('menuitem', { name: '移除项目', exact: true }).click()
    await page.locator('.ant-modal-confirm').getByRole('button', { name: /^取\s*消$/ }).click()
    await page.getByRole('button', { name: '移除已选 (2)', exact: true }).click()
    await expect(page.locator('.ant-modal-confirm-title').filter({ hasText: '移除已选的 2 个视频？' })).toBeVisible()
    await page.locator('.ant-modal-confirm').getByRole('button', { name: /^取\s*消$/ }).click()
    await screenshot('project-library')
    await page.getByRole('button', { name: '0.5 秒', exact: true }).click()
    await page.getByText('PNG · 无损', { exact: true }).click()
    await page.evaluate(() => window.framepick.chooseOutput())
    await page.getByText('图片拼接', { exact: true }).click()
    await page.getByLabel('自动拼接', { exact: true }).click()
    await page.getByLabel('拼接列数', { exact: true }).fill('2')
    await page.getByLabel('拼接行数', { exact: true }).fill('2')
    await page.getByLabel('拼接列数', { exact: true }).blur()
    await waitState(page, s => s.settings.columns === 2 && s.settings.rows === 2 && s.settings.perSheet === 4 && s.settings.autoStitch)
    await screenshot('loaded-state')
    await page.getByRole('button', { name: '开始抽帧 · 2 个视频', exact: true }).click()
    await waitState(page, s => s.jobs.length === 2 && s.jobs.every(j => j.status === 'done'))
    const state = await page.evaluate(() => window.framepick.snapshot())
    for (const job of state.jobs) {
      assert.equal(job.count, 5)
      assert.equal(job.sheets.length, 2)
      const record = JSON.parse(fs.readFileSync(job.manifest, 'utf8'))
      assert.deepEqual(record.frames.map(frame => frame.name), ['0.5s.png', '1s.png', '1.5s.png', '2s.png', '2.5s.png'])
      for (const frame of record.frames) assert(fs.existsSync(frame.path))
    }
    assert.notEqual(state.jobs[0].folder, state.jobs[1].folder)
    await expect(page.locator('.processing-meter .ant-progress')).toHaveAttribute('aria-valuenow', '100')
    await page.getByRole('button', { name: '查看处理队列', exact: true }).click()
    await expect(page.locator('.job-row.highlighted')).toHaveCount(1)
    await expect(page.getByText('处理完成', { exact: true })).toHaveCount(2)
    await screenshot('queue-state')
    await page.getByRole('button', { name: '查看图片', exact: true }).first().click()
    await expect(page.locator('.results-grid img')).toHaveCount(5)
    await page.waitForFunction(() => Array.from(document.querySelectorAll('.results-grid img')).every(image => image.complete && image.naturalWidth > 0))
    await screenshot('results-state')
    // Long press then drag selects an inclusive range, and can also remove a range.
    const firstFrame = await page.locator('.results-grid img').nth(0).boundingBox()
    const fourthFrame = await page.locator('.results-grid img').nth(3).boundingBox()
    await page.mouse.move(firstFrame.x + firstFrame.width / 2, firstFrame.y + firstFrame.height / 2)
    await page.mouse.down()
    await page.waitForTimeout(450)
    await page.mouse.move(fourthFrame.x + fourthFrame.width / 2, fourthFrame.y + fourthFrame.height / 2, { steps: 12 })
    await page.mouse.up()
    await expect(page.locator('.results-grid figure.selected')).toHaveCount(4)
    const thirdFrame = await page.locator('.results-grid img').nth(2).boundingBox()
    await page.mouse.move(firstFrame.x + firstFrame.width / 2, firstFrame.y + firstFrame.height / 2)
    await page.mouse.down()
    await page.waitForTimeout(450)
    await page.mouse.move(thirdFrame.x + thirdFrame.width / 2, thirdFrame.y + thirdFrame.height / 2, { steps: 10 })
    await page.mouse.up()
    await expect(page.locator('.results-grid figure.selected')).toHaveCount(1)
    await page.getByRole('button', { name: '清空选择', exact: true }).click()
    await page.getByRole('checkbox', { name: '1s.png', exact: true }).check()
    await page.getByRole('button', { name: '拼接所选图片', exact: true }).click()
    const board = page.locator('.board-settings')
    await expect(page.locator('.story-cell img')).toHaveCount(1)
    await board.getByLabel('拼接预设', { exact: true }).click()
    await page.getByText('六宫格 · 2 行 × 3 列', { exact: true }).click()
    await board.getByLabel('故事板备注区', { exact: true }).click()
    const note = '镜头一：夜色渐深\n人物停下脚步，望向远处。'
    await page.getByRole('textbox', { name: '1s.png 备注', exact: true }).fill(note)
    await expect(page.locator('.story-cell')).toHaveCount(3)
    await expect(page.locator('.story-cell.empty')).toHaveCount(2)
    await page.getByRole('button', { name: '生成当前拼接图', exact: true }).click()
    await expect(page.getByText('拼接图已保存', { exact: true })).toBeVisible({ timeout: 20000 })
    const stitched = await page.evaluate(() => window.framepick.snapshot())
    assert(stitched.jobs.every(job => job.completed === 5 && job.total === 5 && job.status === 'done'))
    await page.getByRole('tab', { name: '拼接图 (3)', exact: true }).click()
    await expect(page.locator('.sheets-list img')).toHaveCount(3)
    const selectedJob = stitched.jobs.find(job => job.sheets.length === 3)
    let saved = JSON.parse(fs.readFileSync(selectedJob.manifest, 'utf8'))
    assert.equal(saved.notes['1s.png'], note)
    assert.deepEqual(saved.stitchHistory.at(-1).names, ['1s.png'])
    assert.equal(saved.stitchDraft.rows, 2)
    assert.equal(saved.stitchDraft.columns, 3)
    assert.equal(saved.stitchDraft.notesEnabled, true)
    const noteSize = await application.evaluate(({ nativeImage }, file) => nativeImage.createFromPath(file).getSize(), saved.sheets.at(-1))
    assert.deepEqual(noteSize, { width: 1472, height: 412 })
    await screenshot('sheets-state')
    await page.locator('.ant-modal-close').click()
    await expect(page.locator('.results-modal')).not.toBeVisible()
    await page.getByRole('button', { name: '查看图片', exact: true }).first().click()
    await page.getByRole('tab', { name: '拼接编辑', exact: true }).click()
    await expect(page.getByRole('textbox', { name: '1s.png 备注', exact: true })).toHaveValue(note)
    await expect(page.locator('.story-cell img')).toHaveCount(5)
    await expect(page.locator('.story-cell.empty')).toHaveCount(1)
    await page.getByRole('textbox', { name: '0.5s.png 备注', exact: true }).fill('开场：城市灯光亮起。')
    await page.getByRole('textbox', { name: '1.5s.png 备注', exact: true }).fill('动作：镜头缓缓向前。')
    await board.getByLabel('拼接预设', { exact: true }).click()
    await page.getByText('九宫格 · 3 行 × 3 列', { exact: true }).click()
    await expect(page.locator('.story-cell')).toHaveCount(6)
    await expect(page.locator('.story-cell.empty')).toHaveCount(1)
    await screenshot('storyboard-editor')
    assert(await page.evaluate(() => {
      const preview = document.querySelector('.board-scroll').getBoundingClientRect()
      const info = document.querySelector('.board-page-info').getBoundingClientRect()
      return preview.bottom <= info.top + 1 && info.bottom < window.innerHeight
    }))
    await board.getByLabel('拼接行数', { exact: true }).fill('2')
    await board.getByLabel('拼接列数', { exact: true }).fill('4')
    await board.getByLabel('拼接图片宽度', { exact: true }).fill('240')
    await board.getByLabel('拼接图片宽度', { exact: true }).blur()
    await expect(page.locator('.story-cell')).toHaveCount(8)
    await expect(page.locator('.story-cell.empty')).toHaveCount(3)
    await board.getByLabel('故事板备注区', { exact: true }).click()
    await expect(page.locator('.story-cell textarea')).toHaveCount(0)
    await page.getByRole('button', { name: '生成当前拼接图', exact: true }).click()
    await expect(page.locator('.sheets-list img')).toHaveCount(4, { timeout: 20000 })
    saved = JSON.parse(fs.readFileSync(selectedJob.manifest, 'utf8'))
    assert.equal(saved.notes['0.5s.png'], '开场：城市灯光亮起。')
    assert.equal(saved.notes['1s.png'], note)
    assert.equal(saved.stitchDraft.notesEnabled, false)
    assert.equal(saved.stitchHistory.at(-1).names.length, 5)
    const ordinarySize = await application.evaluate(({ nativeImage }, file) => nativeImage.createFromPath(file).getSize(), saved.sheets.at(-1))
    assert.deepEqual(ordinarySize, { width: 1000, height: 332 })
    await page.getByRole('tab', { name: '拼接编辑', exact: true }).click()
    await board.getByLabel('故事板备注区', { exact: true }).click()
    // Font and minimum height must change the visible editor, not just export size.
    await board.getByLabel('备注字号', { exact: true }).fill('8')
    await board.getByLabel('备注字号', { exact: true }).blur()
    const text = page.getByRole('textbox', { name: '1s.png 备注', exact: true })
    await expect(text).toHaveCSS('font-size', '8px')
    await board.getByLabel('备注字号', { exact: true }).fill('28')
    await board.getByLabel('备注字号', { exact: true }).blur()
    await expect(text).toHaveCSS('font-size', '28px')
    await board.getByLabel('备注区高度', { exact: true }).fill('300')
    await board.getByLabel('备注区高度', { exact: true }).blur()
    await expect(text).toHaveCSS('height', '300px')
    await board.getByLabel('备注区高度', { exact: true }).fill('96')
    await board.getByLabel('备注区高度', { exact: true }).blur()
    await text.fill('Storyboard notes should wrap at the chosen font size. '.repeat(15))
    await expect.poll(async () => text.evaluate(node => node.clientHeight)).toBeGreaterThan(300)
    await expect.poll(async () => text.evaluate(node => node.scrollHeight - node.clientHeight)).toBeLessThanOrEqual(1)
    await text.fill('过长的备注'.repeat(190))
    await expect.poll(async () => text.evaluate(node => node.clientHeight)).toBeGreaterThan(300)
    await expect.poll(async () => text.evaluate(node => node.scrollHeight - node.clientHeight)).toBeLessThanOrEqual(1)
    const rowNotes = await page.locator('.story-cell textarea').evaluateAll(nodes => nodes.map(node => ({ height: node.clientHeight, scroll: node.scrollHeight, font: getComputedStyle(node).fontSize })))
    assert(rowNotes[0].height === rowNotes[1].height && rowNotes[1].height === rowNotes[2].height && rowNotes[2].height === rowNotes[3].height)
    assert(rowNotes[1].height > rowNotes[4].height)
    assert(rowNotes.every(node => node.scroll <= node.height + 1), JSON.stringify(rowNotes))
    assert(rowNotes.every(node => node.font === '28px'))
    await screenshot('notes-auto-height')
    await page.getByRole('button', { name: '生成当前拼接图', exact: true }).click()
    await expect(page.locator('.sheets-list img')).toHaveCount(5, { timeout: 20000 })
    saved = JSON.parse(fs.readFileSync(selectedJob.manifest, 'utf8'))
    const tallSheet = await application.evaluate(({ nativeImage }, file) => nativeImage.createFromPath(file).getSize(), saved.sheets.at(-1))
    assert(tallSheet.height > 1000)
    await page.getByRole('tab', { name: '拼接编辑', exact: true }).click()
    await text.fill(note)
    await board.getByLabel('备注字号', { exact: true }).fill('14')
    await board.getByLabel('备注字号', { exact: true }).blur()
    // Choosing page two exports only that page.
    await board.getByLabel('拼接行数', { exact: true }).fill('2')
    await board.getByLabel('拼接列数', { exact: true }).fill('2')
    await board.getByLabel('拼接列数', { exact: true }).blur()
    await expect(page.locator('.story-cell img')).toHaveCount(4)
    await page.locator('.board-page-info .ant-pagination-item-2').click()
    await expect(page.locator('.story-cell img')).toHaveCount(1)
    await expect(page.locator('.story-cell.empty')).toHaveCount(1)
    await page.getByRole('button', { name: '生成当前拼接图', exact: true }).click()
    await expect(page.locator('.sheets-list img')).toHaveCount(6, { timeout: 20000 })
    saved = JSON.parse(fs.readFileSync(selectedJob.manifest, 'utf8'))
    assert.deepEqual(saved.stitchHistory.at(-1).names, ['2.5s.png'])
    assert.equal(saved.sheetRecipes[saved.sheets.at(-1)].offset, 4)
    // Reopen a particular exported sheet and preserve its original frame/notes recipe.
    await page.locator('.sheets-list figure').nth(2).locator('img').click()
    await expect(page.locator('.sheets-list figure').nth(2)).toHaveClass(/selected/)
    await page.locator('.sheets-list figure').nth(2).getByRole('button', { name: '编辑这张', exact: true }).click()
    await expect(page.locator('.story-cell img')).toHaveCount(1)
    await expect(text).toHaveValue(note)
    await expect(board.getByLabel('拼接列数', { exact: true })).toHaveValue('3')
    await text.fill(note + '\n编辑已导出的这一张。')
    await page.getByRole('button', { name: '生成当前拼接图', exact: true }).click()
    await expect(page.locator('.sheets-list img')).toHaveCount(7, { timeout: 20000 })
    saved = JSON.parse(fs.readFileSync(selectedJob.manifest, 'utf8'))
    assert.deepEqual(saved.sheetRecipes[saved.sheets.at(-1)].names, ['1s.png'])
    assert.equal(saved.sheetRecipes[saved.sheets[2]].notes['1s.png'], note)
    // The top toolbar remains the all-frames batch export.
    await page.getByRole('tab', { name: '拼接编辑', exact: true }).click()
    await board.getByLabel('拼接行数', { exact: true }).fill('2')
    await board.getByLabel('拼接列数', { exact: true }).fill('2')
    await board.getByLabel('拼接列数', { exact: true }).blur()
    await page.getByRole('button', { name: '拼接全部图片', exact: true }).click()
    await expect(page.locator('.sheets-list img')).toHaveCount(9, { timeout: 20000 })
    saved = JSON.parse(fs.readFileSync(selectedJob.manifest, 'utf8'))
    assert.equal(saved.stitchHistory.at(-1).names.length, 5)
    await page.getByRole('tab', { name: '拼接编辑', exact: true }).click()
    await page.getByText('全部截图', { exact: true }).click()
    await board.getByLabel('拼接列数', { exact: true }).fill('4')
    await board.getByLabel('拼接列数', { exact: true }).blur()
    await expect(page.locator('.story-cell img')).toHaveCount(5)
    await page.getByRole('textbox', { name: '2s.png 备注', exact: true }).fill('只保存备注，稍后再导出。')
    await page.locator('.ant-modal-close').click()
    await expect(page.locator('.results-modal')).not.toBeVisible()
    saved = JSON.parse(fs.readFileSync(selectedJob.manifest, 'utf8'))
    assert.equal(saved.notes['2s.png'], '只保存备注，稍后再导出。')
    await page.getByRole('button', { name: '抽帧工作台', exact: true }).click()
    await page.locator('.video-row').filter({ hasText: '城市·夜景（测试）' }).click()
    await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1120, 760))
    await page.getByRole('button', { name: '查看导出图片', exact: true }).scrollIntoViewIfNeeded()
    await screenshot('compact-state')
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1))
    await page.getByRole('button', { name: '查看导出图片', exact: true }).click()
    await page.getByRole('tab', { name: '拼接编辑', exact: true }).click()
    await expect(page.locator('.story-cell img')).toHaveCount(5)
    await expect(page.getByRole('textbox', { name: '2s.png 备注', exact: true })).toHaveValue('只保存备注，稍后再导出。')
    await expect(page.getByRole('button', { name: '生成当前拼接图', exact: true })).toBeEnabled()
    await screenshot('storyboard-compact')
    assert(await page.evaluate(() => {
      const info = document.querySelector('.board-page-info').getBoundingClientRect()
      const editor = document.querySelector('.stitch-editor').getBoundingClientRect()
      return info.bottom < window.innerHeight && editor.right < window.innerWidth
    }))
    await page.locator('.ant-modal-close').click()
    await expect(page.locator('.results-modal')).not.toBeVisible()
    // Resize, redraw, and set an exact crop, then verify the real extracted pixels.
    await page.getByRole('button', { name: '裁剪画面', exact: true }).click()
    await expect(page.locator('.crop-stage')).toBeVisible()
    const cropBounds = await page.locator('.crop-stage').boundingBox()
    const corner = await page.locator('.crop-handle.se').boundingBox()
    await page.mouse.move(corner.x + corner.width / 2, corner.y + corner.height / 2)
    await page.mouse.down()
    await page.mouse.move(cropBounds.x + cropBounds.width * .7, cropBounds.y + cropBounds.height * .7, { steps: 8 })
    await page.mouse.up()
    assert(Number(await page.getByLabel('裁剪宽度', { exact: true }).inputValue()) < 400)
    await page.mouse.move(cropBounds.x + cropBounds.width * .9, cropBounds.y + cropBounds.height * .9)
    await page.mouse.down()
    await page.mouse.move(cropBounds.x + cropBounds.width * .1, cropBounds.y + cropBounds.height * .1, { steps: 8 })
    await page.mouse.up()
    await page.getByLabel('裁剪左边距', { exact: true }).fill('48')
    await page.getByLabel('裁剪上边距', { exact: true }).fill('27')
    await page.getByLabel('裁剪宽度', { exact: true }).fill('384')
    await page.getByLabel('裁剪高度', { exact: true }).fill('216')
    await page.getByLabel('裁剪高度', { exact: true }).blur()
    assert(await page.getByRole('button', { name: '应用裁剪区域', exact: true }).evaluate(node => node.getBoundingClientRect().bottom < window.innerHeight))
    await screenshot('video-crop')
    await page.getByRole('button', { name: '应用裁剪区域', exact: true }).click()
    await expect(page.locator('.crop-modal')).not.toBeVisible()
    const cropState = await page.evaluate(() => window.framepick.snapshot())
    const cropVideo = cropState.videos[1]
    assert.deepEqual(cropVideo.crop, { x: .1, y: .1, width: .8, height: .8 })
    assert.equal(cropVideo.override, undefined)
    await page.evaluate(id => window.framepick.enqueue([id]), cropVideo.id)
    await waitState(page, s => s.jobs.length === 3 && s.jobs.every(job => job.status === 'done'))
    const croppedState = await page.evaluate(() => window.framepick.snapshot())
    const cropJob = croppedState.jobs[2]
    const cropManifest = JSON.parse(fs.readFileSync(cropJob.manifest, 'utf8'))
    const croppedSize = await application.evaluate(({ nativeImage }, file) => nativeImage.createFromPath(file).getSize(), cropManifest.frames[0].path)
    assert.deepEqual(croppedSize, { width: 384, height: 216 })
    assert.notEqual(cropJob.folder, croppedState.jobs[1].folder)
    assert.equal(cropJob.settings.conflict, 'batch')
    const checkCrop = spawnSync(path.join(root, '.venv/Scripts/python.exe'), ['-c', 'import sys, av; from PIL import Image, ImageChops; c=av.open(sys.argv[1]); f=min(c.decode(video=0),key=lambda f:abs(float(f.pts*f.time_base)-.5)); a=f.to_image().crop((48,27,432,243)); b=Image.open(sys.argv[2]).convert("RGB"); assert ImageChops.difference(a,b).getbbox() is None; c.close()', second, cropManifest.frames[0].path], { windowsHide: true, encoding: 'utf8' })
    assert.equal(checkCrop.status, 0, checkCrop.stderr)
    await page.getByRole('button', { name: '收起项目 旅行素材', exact: true }).click()
    assert.deepEqual(errors, [])
    await application.close()
    page = await launch()
    const restored = await page.evaluate(() => window.framepick.snapshot())
    assert.equal(restored.videos.length, 2)
    assert.deepEqual(restored.projects.map(project => project.name), ['旅行素材', '短片分镜'])
    assert.equal(restored.projects[0].collapsed, true)
    assert(restored.projects[1].pinnedAt && restored.videos[1].pinnedAt)
    assert.equal(restored.videos[1].projectId, restored.projects[1].id)
    await expect(page.locator('.video-row')).toHaveCount(1)
    assert(restored.jobs.every(job => job.status === 'done'))
    assert.deepEqual(restored.videos[1].crop, { x: .1, y: .1, width: .8, height: .8 })
    const baselineJobs = restored.jobs.length
    if (process.env.FRAMEPICK_ONLINE_SMOKE) {
      const resolved = await page.evaluate(() => window.framepick.resolveLinks('https://www.bilibili.com/video/BV13x41117TL'))
      assert.equal(resolved.added, 1, JSON.stringify(resolved))
      await waitState(page, s => s.videos.length === 3)
      await page.locator('.video-row').filter({ hasText: 'Bilibili' }).click()
      await expect(page.getByRole('button', { name: '下载视频', exact: true })).toBeVisible()
      const resolvedState = await page.evaluate(() => window.framepick.snapshot())
      assert.equal(resolvedState.videos[2].projectId, resolvedState.activeProjectId)
      await application.evaluate(({ dialog }) => { dialog.showOpenDialog = async () => ({ canceled: true, filePaths: [] }) })
      await page.getByRole('button', { name: '下载视频', exact: true }).click()
      assert.equal((await page.evaluate(() => window.framepick.snapshot())).jobs.length, baselineJobs)
      await application.evaluate(({ dialog }, folder) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [folder] }) }, downloadRoot)
      await page.evaluate(async () => { const s = await window.framepick.snapshot(); await window.framepick.saveSettings({ ...s.settings, onlineQuality: 360 }) })
      await page.getByRole('button', { name: '下载视频', exact: true }).click()
      await waitState(page, s => s.jobs.length === baselineJobs + 1 && s.jobs.every(job => job.status === 'done'))
      const downloaded = await page.evaluate(() => window.framepick.snapshot())
      const downloadJob = downloaded.jobs[baselineJobs]
      assert.equal(downloadJob.kind, 'download')
      assert.equal(path.dirname(downloadJob.downloadPath), downloadRoot)
      assert.equal(downloaded.videos[2].downloadedPath, downloadJob.downloadPath)
      assert(fs.statSync(downloadJob.downloadPath).size > 10000)
      assert.equal(downloadJob.manifest, undefined)
      assert.equal(fs.readdirSync(downloadRoot).length, 1)
      await expect(page.locator('.download-summary')).toBeVisible()
      await expect(page.getByRole('button', { name: '再次下载', exact: true })).toBeVisible()
      await screenshot('download-complete')
      await page.evaluate(async () => {
        const s = await window.framepick.snapshot()
        await window.framepick.saveSettings({ ...s.settings, end: 2, onlineQuality: 360, perSheet: 20 })
        await window.framepick.enqueue([s.videos.find(video => video.source === 'online').id])
      })
      await waitState(page, s => s.jobs.length === baselineJobs + 2 && s.jobs.every(job => job.status === 'done'))
      const online = await page.evaluate(() => window.framepick.snapshot())
      const job = online.jobs[baselineJobs + 1]
      assert.equal(job.count, 3)
      assert.equal(job.sheets.length, 1)
      assert(fs.existsSync(downloadJob.downloadPath))
      assert(!fs.readdirSync(path.join(data, 'user-data/cache/downloads')).some(name => fs.readdirSync(path.join(data, 'user-data/cache/downloads', name)).length > 0))
      await screenshot('online-state')
    }
    assert.deepEqual(errors, [])
    await application.close()
    application = null
    const report = { result: 'passed', version: require('../package.json').version, packaged: Boolean(process.env.FRAMEPICK_PACKAGED_EXE), online: Boolean(process.env.FRAMEPICK_ONLINE_SMOKE), checks: ['native import bridge', 'batch deduplication', 'metadata', 'project creation import move rename and folding', 'project persistence', 'long press project drag drop empty folders hover expand and Escape', 'video and project pinning persistence', 'search videos and empty results', 'single batch project removal cancellation confirmations', 'bottom completed progress and jump to specific job', 'settings controls', 'real frame extraction', 'separate output folders', 'automatic paged stitching', 'image protocol', 'selected-image stitching', 'six-grid and nine-grid presets', 'Chinese multiline storyboard notes', 'trimmed empty bottom rows and horizontal blanks', 'visible note height and font', 'automatic equal row note height without scrolling', 'long press drag selection and deselection', 'single page export and all-frames batch export', 'existing sheet recipe editing', 'visual crop gestures pixel settings and exact extracted pixels', 'custom rows columns and canvas dimensions', 'notes persistence and disabling', 'compact layout', 'state restoration', ...(process.env.FRAMEPICK_ONLINE_SMOKE ? ['download only to chosen folder', 'cancel folder selection', 'downloaded video reused for extraction'] : [])], artifacts: artifact, output }
    fs.writeFileSync(path.join(artifact, 'report.json'), JSON.stringify(report, null, 2))
    console.log(JSON.stringify(report))
  } finally {
    if (application) await application.close()
  }
})().catch(error => { console.error(error); process.exitCode = 1 })
