const {_electron:electron,expect}=require('@playwright/test')
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process')
const root=path.resolve(__dirname,'..'),version=require('../package.json').version,artifact=path.join(root,'.test-artifacts',version,'new-features',String(Date.now())),data=path.join(artifact,'user-data'),output=path.join(artifact,'截图'),first=path.join(artifact,'分段样本.mp4'),second=path.join(artifact,'短视频样本.mp4'),backup=path.join(artifact,'工作区备份.json')
fs.mkdirSync(output,{recursive:true})
for(const [file,size,duration] of [[first,'640x360',12],[second,'320x180',8]]){const r=spawnSync(path.join(root,'.tools/ffmpeg.exe'),['-hide_banner','-loglevel','error','-y','-f','lavfi','-i',`testsrc2=duration=${duration}:size=${size}:rate=10`,'-c:v','libx264','-threads','2','-pix_fmt','yuv420p',file],{windowsHide:true,encoding:'utf8'});assert.equal(r.status,0,r.stderr)}
let app,page,primary,job;const cases=[],errors=[]
const snapshot=()=>page.evaluate(()=>window.framepick.snapshot())
const waitState=predicate=>expect.poll(async()=>predicate(await snapshot()),{timeout:60000}).toBe(true)
const record=()=>JSON.parse(fs.readFileSync(job.manifest,'utf8'))
const write=()=>fs.writeFileSync(path.join(artifact,'report.json'),JSON.stringify({version,packaged:!!process.env.FRAMEPICK_PACKAGED_EXE,cases,errors,artifact},null,2))
async function test(name,fn){console.log('TEST '+name);const begin=Date.now();try{const details=await fn();cases.push({name,status:'passed',seconds:(Date.now()-begin)/1000,details});write()}catch(error){cases.push({name,status:'failed',seconds:(Date.now()-begin)/1000,error:error.stack});write();throw error}}
async function launch(){app=await electron.launch({executablePath:process.env.FRAMEPICK_PACKAGED_EXE||require('electron'),args:process.env.FRAMEPICK_PACKAGED_EXE?['--hidden']:[root,'--hidden'],env:{...process.env,FRAMEPICK_TEST_DATA:data,ELECTRON_RENDERER_URL:'',...(process.env.FRAMEPICK_PACKAGED_EXE?{PATH:`${process.env.SystemRoot}\\System32;${process.env.SystemRoot}`}:{})},timeout:60000});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await waitState(s=>s.health.ready);await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await waitState(s=>s.health.ready)}
async function pick(folder){await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},folder)}
async function number(label,value,scope=page){await scope.getByRole('spinbutton',{name:label,exact:true}).fill(String(value));await scope.getByRole('spinbutton',{name:label,exact:true}).press('Tab')}
async function select(label,text,scope=page){await scope.getByLabel(label,{exact:true}).click();await page.locator('.ant-select-dropdown:visible').getByText(text,{exact:true}).click()}
async function capture(name){const png=await app.evaluate(async({BrowserWindow})=>{const wc=BrowserWindow.getAllWindows()[0].webContents;await wc.capturePage(undefined,{stayHidden:true,stayAwake:true});await new Promise(r=>setTimeout(r,150));return(await wc.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG().toString('base64')});fs.writeFileSync(path.join(artifact,name+'.png'),Buffer.from(png,'base64'))}
async function openCrop(){await page.getByRole('button',{name:'抽帧工作台',exact:true}).click();await page.locator(`[data-video-id="${primary.id}"]`).click();await page.getByRole('button',{name:'裁剪画面',exact:true}).click();await expect(page.locator('.crop-modal')).toBeVisible();return page.locator('.crop-modal')}
async function closeResults(){await page.locator('.results-modal .ant-modal-close').click();await expect(page.locator('.results-modal')).not.toBeVisible()}
async function showResults(){await page.getByRole('button',{name:'处理队列',exact:true}).click();await page.locator(`[data-job-id="${job.id}"]`).getByRole('button',{name:'查看图片',exact:true}).click();await expect(page.locator('.results-grid figure')).toHaveCount(11)}
async function readScale(selector){return page.locator(selector).evaluate(el=>{const transform=getComputedStyle(el).transform;return transform==='none'?1:Number(transform.match(/matrix\(([^,]+)/)[1])})}
async function pan(selector,mode='space'){const stage=page.locator(selector),box=await stage.boundingBox();await page.mouse.move(box.x+box.width*.65,box.y+box.height*.5);if(mode==='space')await page.keyboard.down('Space');await page.mouse.down({button:mode==='middle'?'middle':'left'});if(mode==='long')await page.waitForTimeout(500);await page.mouse.move(box.x+box.width*.25,box.y+box.height*.4,{steps:8});await page.mouse.up({button:mode==='middle'?'middle':'left'});if(mode==='space')await page.keyboard.up('Space');assert((await stage.evaluate(el=>el.scrollLeft))>30)}
(async()=>{try{
 await launch()
 await test('磁盘预估、元数据与分段裁剪编辑',async()=>{
  await page.evaluate(async files=>{await window.framepick.addFiles(files);const s=await window.framepick.snapshot();await window.framepick.saveSettings({...s.settings,format:'png',interval:1,autoStitch:false,conflict:'batch',thumbWidth:240,rows:2,columns:2})},[first,second]);await waitState(s=>s.videos.length===2&&s.videos.every(v=>v.status==='ready'));primary=(await snapshot()).videos[0]
  await pick(output);await page.getByRole('button',{name:output,exact:true}).count().catch(()=>0);await page.evaluate(()=>window.framepick.chooseOutput());await expect(page.getByLabel('磁盘空间预估')).toContainText('可用空间')
  const estimate=await page.evaluate(id=>window.framepick.estimate([id]),primary.id);assert.equal(estimate.frames,11);assert(estimate.maxBytes>estimate.minBytes&&estimate.freeBytes>estimate.maxBytes)
  const crop=await openCrop();await number('裁剪左边距',64,crop);await number('裁剪上边距',36,crop);await number('裁剪宽度',512,crop);await number('裁剪高度',288,crop)
  await crop.getByRole('button',{name:'添加裁剪时段',exact:true}).click();await number('裁剪时段开始',1,crop);await number('裁剪时段结束',5,crop);await number('裁剪左边距',0,crop);await number('裁剪上边距',0,crop);await number('裁剪宽度',320,crop);await number('裁剪高度',360,crop)
  await crop.getByRole('button',{name:'添加裁剪时段',exact:true}).click();await number('裁剪时段结束',10,crop);await number('裁剪左边距',0,crop);await number('裁剪上边距',90,crop);await number('裁剪宽度',640,crop);await number('裁剪高度',180,crop)
  await crop.getByRole('button',{name:'保存裁剪预设',exact:true}).click();await page.getByRole('textbox',{name:'裁剪预设名称',exact:true}).fill('分镜分段');await page.getByRole('button',{name:'保存预设',exact:true}).click();await waitState(s=>s.templates.some(t=>t.name==='裁剪 · 分镜分段'))
  await crop.getByRole('button',{name:'应用到已选视频',exact:true}).click();await expect(page.locator('.ant-modal-confirm-title')).toContainText('把裁剪应用到已选视频');await page.locator('.ant-modal-confirm').getByRole('button',{name:'应用裁剪',exact:true}).click();await waitState(s=>s.videos[1].cropSegments?.[1].end===8)
  await capture('temporal-crop');await crop.getByRole('button',{name:'应用裁剪区域',exact:true}).click();await expect(crop).not.toBeVisible();assert.deepEqual((await snapshot()).videos[0].cropSegments.map(s=>[s.start,s.end]),[[1,5],[6,10]])
  return {estimate,normalizedBatchSecondEnd:8}
 })
 await test('裁剪预览边界、缩放和三种拖动方式',async()=>{
  const crop=await openCrop();for(const [seconds,width,height]of[[.5,512,288],[1,320,360],[5,320,360],[5.5,512,288],[6,640,180],[10,640,180],[10.5,512,288]]){await number('裁剪预览秒',seconds,crop);await expect(crop.getByRole('spinbutton',{name:'裁剪宽度',exact:true})).toHaveValue(String(width));await expect(crop.getByRole('spinbutton',{name:'裁剪高度',exact:true})).toHaveValue(String(height));await expect.poll(()=>crop.locator('video').evaluate(v=>v.currentTime)).toBeCloseTo(seconds,2)}
  await crop.getByRole('button',{name:'适合画面',exact:true}).click();assert((await crop.locator('.crop-preview-wrap').evaluate(el=>el.scrollWidth-el.clientWidth))<5)
  const before=await readScale('.crop-stage');await page.keyboard.press('Control+Equal');await expect.poll(()=>readScale('.crop-stage')).toBeGreaterThan(before)
  await crop.getByRole('button',{name:'100%',exact:true}).click();await page.keyboard.press('Control+Equal');await page.keyboard.press('Control+Equal');await page.keyboard.press('Control+Equal');await pan('.crop-preview-wrap','space');await pan('.crop-preview-wrap','middle');await pan('.crop-preview-wrap','long')
  assert.equal(await crop.getByRole('spinbutton',{name:'裁剪宽度',exact:true}).inputValue(),'512');await crop.getByRole('spinbutton',{name:'裁剪宽度',exact:true}).focus();await page.keyboard.press('Escape');await expect(crop).not.toBeVisible()
 })
 await test('分段实际抽帧与不同画幅像素核对',async()=>{
  await page.getByRole('button',{name:/^开始抽帧/}).click();await waitState(s=>s.jobs.length===2&&s.jobs.every(j=>j.status==='done'));const s=await snapshot();job=s.jobs.find(j=>j.videoId===primary.id)
  const check=spawnSync(path.join(root,'.venv/Scripts/python.exe'),[path.join(root,'scripts/verify_real_frames.py'),first,job.manifest],{windowsHide:true,encoding:'utf8'});assert.equal(check.status,0,check.stdout+check.stderr)
  assert.equal(record().frames.length,11);return {frames:11,pixels:check.stdout.trim(),secondCount:s.jobs.find(j=>j.videoId!==primary.id).count}
 })
 await test('可配置快捷键、滚轮方式、重复组合校验',async()=>{
  await page.getByRole('button',{name:'画面操作快捷键',exact:true}).click();const settings=page.locator('.ant-modal').filter({has:page.getByRole('textbox',{name:'放大快捷键',exact:true})})
  for(const [label,chord]of[['放大','Control+k'],['缩小','Control+k']]){await settings.getByRole('textbox',{name:label+'快捷键',exact:true}).focus();await page.keyboard.press(chord)}
  await settings.getByRole('button',{name:/^保\s*存$/}).click();await expect(settings.getByText('快捷键重复，请为每个操作设置不同组合。',{exact:true})).toBeVisible()
  for(const [label,chord]of[['缩小','Control+j'],['适合画面','F9'],['实际大小','F10'],['退出查看/编辑','F8']]){await settings.getByRole('textbox',{name:label+'快捷键',exact:true}).focus();await page.keyboard.press(chord)}
  await select('滚轮缩放方式','Alt + 滚轮',settings);await settings.getByRole('button',{name:/^保\s*存$/}).click();await waitState(s=>s.viewport.zoomIn==='Control+KeyK'&&s.viewport.wheel==='alt'&&s.viewport.close==='F8')
 })
 await test('选图快捷键与原图查看器的缩放、平移、退出',async()=>{
  await showResults();await page.locator('[data-frame-index="0"] img').click();await page.keyboard.down('Shift');await page.locator('[data-frame-index="3"] img').click();await page.keyboard.up('Shift');await expect(page.locator('.results-toolbar>span')).toContainText('已选择 4 张')
  await page.locator('[data-frame-index="3"]').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Space');await expect(page.locator('.results-toolbar>span')).toContainText('已选择 5 张');await page.keyboard.press('Control+a');await expect(page.locator('.results-toolbar>span')).toContainText('已选择 11 张')
  await page.locator('[data-frame-index="0"] img').dblclick();await expect(page.locator('.image-viewer-modal')).toBeVisible();await expect.poll(()=>page.locator('.image-viewer-canvas img').evaluate(i=>i.naturalWidth)).toBe(320)
  const before=await readScale('.image-viewer-canvas img');await page.keyboard.press('Control+k');await expect.poll(()=>readScale('.image-viewer-canvas img')).toBeGreaterThan(before);await page.keyboard.press('Control+j');await page.keyboard.press('F10')
  const stage=page.locator('.image-viewer-stage'),box=await stage.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+100);await page.keyboard.down('Alt');await page.mouse.wheel(0,-120);await page.keyboard.up('Alt');await expect.poll(()=>readScale('.image-viewer-canvas img')).toBeGreaterThan(1)
  for(let i=0;i<8;i++)await page.keyboard.press('Control+k');await pan('.image-viewer-stage','space');await page.keyboard.press('F9');assert((await stage.evaluate(e=>e.scrollWidth-e.clientWidth))<5)
  await page.keyboard.press('ArrowRight');await expect(page.locator('.image-viewer-modal .ant-modal-title')).toContainText('2s.png');await page.keyboard.press('Escape');await expect(page.locator('.image-viewer-modal')).toBeVisible();await page.keyboard.press('F8');await expect(page.locator('.image-viewer-modal')).not.toBeVisible();await expect(page.locator('.results-modal')).toBeVisible()
  await page.getByRole('button',{name:'清空选择',exact:true}).click()
 })
 await test('故事板字段、文字样式、拖动顺序与单张替换',async()=>{
  await page.getByRole('tab',{name:'拼接编辑',exact:true}).click();await expect(page.locator('.story-cell img')).toHaveCount(4);await page.getByRole('switch',{name:'故事板备注区',exact:true}).click();await page.getByRole('checkbox',{name:'使用镜号 / 画面 / 动作 / 对白字段',exact:true}).check();await page.locator('.story-cell img').first().click()
  for(const [label,text]of[['镜号','A01'],['画面','站在门口'],['动作','推开门'],['对白','你好']])await page.getByRole('textbox',{name:'1s.png '+label,exact:true}).fill(text)
  await select('备注对齐','右对齐');await select('备注字体','Arial · 中文用雅黑');await number('备注字号',24);await page.getByLabel('备注文字颜色',{exact:true}).fill('#d03020');await page.getByLabel('备注背景颜色',{exact:true}).fill('#fff0e0')
  await page.locator('[data-frame="1s.png"] img').dragTo(page.locator('[data-frame="2s.png"] img'));await expect.poll(()=>page.locator('.story-cell[data-frame]').evaluateAll(e=>e.map(n=>n.dataset.frame))).toEqual(['2s.png','1s.png','3s.png','4s.png']);await page.locator('[data-frame="1s.png"] img').click();await page.getByRole('button',{name:/后\s*移/}).click();await expect.poll(()=>page.locator('.story-cell[data-frame]').evaluateAll(e=>e.map(n=>n.dataset.frame))).toEqual(['2s.png','3s.png','1s.png','4s.png'])
  await page.locator('[data-frame="1s.png"] img').click();await page.getByRole('button',{name:'替换图片',exact:true}).click();await page.locator('.replacement-grid button').filter({hasText:'8s.png'}).click();await expect(page.locator('[data-frame="8s.png"]')).toBeVisible()
  await expect.poll(()=>page.getByRole('textbox',{name:'3s.png 备注',exact:true}).evaluate(t=>t.scrollHeight<=t.clientHeight+1)).toBe(true)
  await page.getByRole('button',{name:'保存模板',exact:true}).click();await page.getByRole('textbox',{name:'故事板模板名称',exact:true}).fill('暖色故事板');await page.locator('.ant-modal').filter({has:page.getByRole('textbox',{name:'故事板模板名称',exact:true})}).getByRole('button',{name:'保存模板',exact:true}).click();await waitState(s=>s.templates.some(t=>t.name==='暖色故事板'))
  await capture('storyboard-fields-order');return {order:await page.locator('.story-cell[data-frame]').evaluateAll(e=>e.map(n=>n.dataset.frame))}
 })
 await test('拼接编辑快捷键、文字输入保护和导出配方',async()=>{
  const note=page.getByRole('textbox',{name:'3s.png 备注',exact:true});await note.focus();const before=await readScale('.storyboard-grid');await page.keyboard.press('Control+k');assert.equal(await readScale('.storyboard-grid'),before)
  await page.locator('.board-zoom button').filter({hasText:'100%'}).click();await page.keyboard.press('Control+k');await expect.poll(()=>readScale('.storyboard-grid')).toBeGreaterThan(1);await page.keyboard.press('F9');assert((await page.locator('.board-scroll').evaluate(el=>el.scrollWidth-el.clientWidth))<5)
  await page.getByRole('button',{name:'生成当前拼接图',exact:true}).click();await expect(page.locator('.sheets-list img')).toHaveCount(1,{timeout:60000});const manifest=record(),recipe=manifest.sheetRecipes[manifest.sheets[0]];assert.deepEqual(recipe.names,['2s.png','3s.png','8s.png','4s.png']);assert.equal(recipe.settings.noteAlign,'right');assert.equal(recipe.settings.noteColor,'#d03020');assert.equal(manifest.notes['1s.png'],'镜号：A01\n画面：站在门口\n动作：推开门\n对白：你好')
  await page.getByRole('button',{name:'编辑这张',exact:true}).click();await expect(page.getByRole('tab',{name:'拼接编辑',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.getByRole('radio',{name:'当前已选拼接图',exact:true})).toBeChecked();await expect.poll(()=>page.locator('.story-cell[data-frame]').evaluateAll(e=>e.map(n=>n.dataset.frame))).toEqual(recipe.names);await page.keyboard.press('F8');await expect(page.getByRole('tab',{name:'抽帧图片',exact:true})).toHaveAttribute('aria-selected','true');await page.keyboard.press('F8');await expect(page.locator('.results-modal')).not.toBeVisible();return {recipe}
 })
 await test('队列搜索筛选、批量归档、恢复与缺图诊断',async()=>{
  await page.getByRole('button',{name:'处理队列',exact:true}).click();await page.getByRole('textbox',{name:'搜索队列',exact:true}).fill('分段样本');await expect(page.locator('.job-row')).toHaveCount(1);await select('队列状态筛选','失败');await expect(page.locator('.job-row')).toHaveCount(0);await select('队列状态筛选','已完成');await page.getByRole('checkbox',{name:'选择筛选结果',exact:true}).check();await page.getByRole('button',{name:'归档所选记录',exact:true}).click();await waitState(s=>s.jobs.length===1)
  await page.getByRole('button',{name:'设置与维护',exact:true}).click();await page.getByRole('button',{name:'恢复归档记录',exact:true}).click();await waitState(s=>s.jobs.length===2);await page.getByRole('button',{name:/^完\s*成$/}).click()
  await page.getByRole('checkbox',{name:'选择筛选结果',exact:true}).check();await page.getByRole('button',{name:'归档所选记录',exact:true}).click();await waitState(s=>s.jobs.length===1)
  const missing=record().frames[1].path;fs.renameSync(missing,missing+'.missing');await pick(job.folder);await page.getByRole('button',{name:'重新导入结果',exact:true}).click();await waitState(s=>s.jobs.length===2);job=(await snapshot()).jobs.find(j=>j.videoId===primary.id);assert.equal(job.missing,1)
  await page.locator(`[data-job-id="${job.id}"]`).getByRole('button',{name:'查看图片',exact:true}).click();await expect(page.getByText('1 张源图缺失，已保留备注与记录。',{exact:true})).toBeVisible();assert.equal(record().notes['1s.png'],'镜号：A01\n画面：站在门口\n动作：推开门\n对白：你好');await closeResults();fs.renameSync(missing+'.missing',missing)
  await page.getByRole('textbox',{name:'搜索队列',exact:true}).fill('');return {missingDiagnostic:1,notesRestored:true}
 })
 await test('工作区备份、合并导入、访问状态排除与素材重新定位',async()=>{
  await page.evaluate(async()=>{const s=await window.framepick.snapshot();await window.framepick.saveSettings({...s.settings,cookiePath:'TEST_COOKIE_PATH'});await window.framepick.createProject('备份项目')})
  await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file})},backup);await page.getByRole('button',{name:'设置与维护',exact:true}).click();await page.getByRole('button',{name:'导出工作区备份',exact:true}).click();await expect.poll(()=>fs.existsSync(backup)).toBe(true);assert(!fs.readFileSync(backup,'utf8').includes('TEST_COOKIE_PATH'));const saved=JSON.parse(fs.readFileSync(backup,'utf8'));assert(saved.drafts&&saved.workspace.templates.length===2)
  fs.renameSync(first,first+'.moved.mp4');await pick(backup);await page.getByRole('button',{name:'导入工作区备份',exact:true}).click();await waitState(s=>s.videos.length===4);const imported=(await snapshot()).videos.find(v=>v.id!==primary.id&&v.name===primary.name);assert.equal(imported.status,'error');assert.equal((await snapshot()).viewport.close,'F8')
  await page.getByRole('button',{name:/^完\s*成$/}).click();await page.getByRole('button',{name:'抽帧工作台',exact:true}).click();await page.locator(`[data-video-id="${imported.id}"]`).click();await pick(first+'.moved.mp4');await page.getByRole('button',{name:'重新定位视频',exact:true}).click();await waitState(s=>s.videos.find(v=>v.id===imported.id).status==='ready');fs.renameSync(first+'.moved.mp4',first);return {projects:(await snapshot()).projects.length,templates:(await snapshot()).templates.length,backupBytes:fs.statSync(backup).size}
 })
 await test('队列批量取消和重试保留已完成图片',async()=>{
  await page.getByRole('button',{name:'处理队列',exact:true}).click();await select('队列状态筛选','全部状态');await page.getByRole('textbox',{name:'搜索队列',exact:true}).fill('')
  const before=(await snapshot()).jobs.length;await page.evaluate(async()=>{const s=await window.framepick.snapshot();await window.framepick.saveSettings({...s.settings,interval:.004,start:0,end:null,format:'png',maxWidth:80,conflict:'batch',autoStitch:false,deduplicate:false,sampling:'interval'});await window.framepick.enqueue(s.videos.slice(0,2).map(v=>v.id))});await waitState(s=>s.jobs.length===before+2&&s.jobs[before].completed>5)
  const ids=(await snapshot()).jobs.slice(before).map(j=>j.id);for(const id of ids)await page.locator(`[data-job-id="${id}"]`).getByRole('checkbox').check();await page.getByRole('button',{name:'批量取消',exact:true}).click();await waitState(s=>s.jobs.filter(j=>ids.includes(j.id)).every(j=>j.status==='cancelled'))
  const partial=(await snapshot()).jobs.find(j=>j.id===ids[0]);const frames=JSON.parse(fs.readFileSync(partial.manifest,'utf8')).frames;assert(frames.length>0);const stamps=frames.map(f=>[f.path,fs.statSync(f.path).mtimeMs]);for(const id of ids)await page.locator(`[data-job-id="${id}"]`).getByRole('checkbox').check();await page.getByRole('button',{name:'重试失败/取消任务',exact:true}).click();await waitState(s=>s.jobs.filter(j=>ids.includes(j.id)).every(j=>j.status==='done'));assert(stamps.every(([file,stamp])=>fs.statSync(file).mtimeMs===stamp));return {jobs:2,preserved:stamps.length,counts:(await snapshot()).jobs.filter(j=>ids.includes(j.id)).map(j=>j.count)}
 })
 await test('解析器更新完整性验证、失败保护与回退',async()=>{
  const decoderBytes=fs.readFileSync(path.join(root,'.tools/yt-dlp.exe')),decoderSum=crypto.createHash('sha256').update(decoderBytes).digest('hex')
  await app.evaluate((_,fixture)=>{
    const bytes=Buffer.from(fixture.base64,'base64'),sum=fixture.sum
    global.__originalFetch=global.fetch;global.__badSum=true
    global.fetch=async url=>{if(String(url).includes('api.github.com'))return new Response(JSON.stringify({tag_name:'2026.08.19',assets:[{name:'yt-dlp.exe',browser_download_url:'https://github.com/yt-dlp/yt-dlp/releases/download/2026.08.19/yt-dlp.exe'},{name:'SHA2-256SUMS',browser_download_url:'https://github.com/yt-dlp/yt-dlp/releases/download/2026.08.19/SHA2-256SUMS'}]}));if(String(url).endsWith('SHA2-256SUMS'))return new Response((global.__badSum?'0'.repeat(64):sum)+'  yt-dlp.exe\n');return new Response(bytes)}
  },{base64:decoderBytes.toString('base64'),sum:decoderSum})
  let failed=await page.evaluate(async()=>{try{await window.framepick.updateDecoder();return false}catch(e){return e.message.includes('校验失败')}});assert(failed);assert(!fs.existsSync(path.join(data,'decoder/yt-dlp.exe')))
  await app.evaluate(()=>{global.__badSum=false});await page.evaluate(()=>window.framepick.updateDecoder());let status=await page.evaluate(()=>window.framepick.decoderStatus());assert.equal(status.version,'2026.08.19');assert(status.canRollback)
  const installed=path.join(data,'decoder/yt-dlp.exe'),stamp=crypto.createHash('sha256').update(fs.readFileSync(installed)).digest('hex');await app.evaluate(()=>{global.fetch=async()=>{throw new Error('Simulated network failure')}});failed=await page.evaluate(async()=>{try{await window.framepick.updateDecoder();return false}catch{return true}});assert(failed);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(installed)).digest('hex'),stamp)
  await page.evaluate(()=>window.framepick.rollbackDecoder());assert.equal(crypto.createHash('sha256').update(fs.readFileSync(installed)).digest('hex'),stamp);await app.evaluate(()=>{global.fetch=global.__originalFetch});return {checksumRejected:true,failedUpdatePreserved:true,rollbackValidated:true}
 })
 await test('设置、模板、分段、配方和更新后的启动恢复',async()=>{await app.close();await launch();const s=await snapshot();assert.equal(s.viewport.close,'F8');assert.equal(s.viewport.zoomIn,'Control+KeyK');assert(s.templates.length>=2);assert(s.videos.some(v=>v.cropSegments?.length===2));assert(s.jobs.length>=2);assert.equal(errors.length,0);return {videos:s.videos.length,jobs:s.jobs.length,templates:s.templates.length}})
 console.log(JSON.stringify({result:'passed',cases:cases.length,artifact}));write()
}catch(error){console.error(error);process.exitCode=1;try{await capture('failed')}catch{}}finally{if(app)await app.close()}})()
