const {_electron:electron,expect}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path')
const root=path.resolve(__dirname,'..'),version=require('../package.json').version,base=path.join(root,'.test-artifacts',version,'pressure'),reports=fs.readdirSync(base).map(name=>path.join(base,name,'report.json')).filter(file=>fs.existsSync(file)),pressure=JSON.parse(fs.readFileSync(reports.sort().at(-1),'utf8')),artifact=path.join(root,'.test-artifacts',version,'pressure-ui',String(Date.now())),data=path.join(artifact,'user-data');fs.mkdirSync(artifact,{recursive:true})
const cases=[],errors=[];let app,page
const snapshot=()=>page.evaluate(()=>window.framepick.snapshot())
const waitState=predicate=>expect.poll(async()=>predicate(await snapshot()),{timeout:60000}).toBe(true)
async function pick(file){await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},file)}
async function test(name,fn){console.log('TEST '+name);const start=Date.now();try{const details=await fn();cases.push({name,status:'passed',seconds:(Date.now()-start)/1000,details})}catch(error){cases.push({name,status:'failed',error:error.stack});throw error}finally{fs.writeFileSync(path.join(artifact,'report.json'),JSON.stringify({cases,errors,artifact,pressure:pressure.artifact,packaged:!!process.env.FRAMEPICK_PACKAGED_EXE},null,2))}}
(async()=>{try{
 app=await electron.launch({executablePath:process.env.FRAMEPICK_PACKAGED_EXE||require('electron'),args:process.env.FRAMEPICK_PACKAGED_EXE?['--hidden']:[root,'--hidden'],env:{...process.env,FRAMEPICK_TEST_DATA:data,ELECTRON_RENDERER_URL:'',...(process.env.FRAMEPICK_PACKAGED_EXE?{PATH:`${process.env.SystemRoot}\\System32;${process.env.SystemRoot}`}:{})},timeout:60000});page=await app.firstWindow();page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));await waitState(s=>s.health.ready);await page.emulateMedia({reducedMotion:'reduce'});await page.reload()
 await test('实际4K千图结果的虚拟列表、翻页和原图读取',async()=>{
  await pick(pressure.cases[0].job.folder);await page.evaluate(()=>window.framepick.importResults());await page.getByRole('button',{name:'处理队列',exact:true}).click();await page.getByRole('button',{name:'查看图片',exact:true}).click();await expect(page.locator('.results-grid img').first()).toBeVisible();const count=await page.locator('.results-grid img').count();assert(count<60&&count>=12)
  for(const index of [0,12,24,36,48,59]){await page.locator('.results-grid').evaluate((el,index)=>{el.scrollTop=Math.floor(index/(innerWidth<=1300?3:4))*198},index);const image=page.locator(`[data-frame-index="${index}"] img`);await image.scrollIntoViewIfNeeded();await expect.poll(()=>image.evaluate(i=>i.complete&&i.naturalWidth>0&&i.naturalWidth<=480)).toBe(true)}
  await page.locator('.results-modal .ant-pagination-item-2').first().click();await expect(page.locator('[data-frame-index="0"] figcaption')).toContainText('0.061s.png');await page.locator('[data-frame-index="0"] img').dblclick();await expect.poll(()=>page.locator('.image-viewer-canvas img').evaluate(i=>i.naturalWidth)).toBe(3840);await page.keyboard.press('Escape');await expect(page.locator('.image-viewer-modal')).not.toBeVisible()
  await page.getByRole('tab',{name:'拼接编辑',exact:true}).click();await expect(page.locator('.story-cell img')).toHaveCount(9);await expect.poll(()=>page.locator('.story-cell img').evaluateAll(images=>images.every(i=>i.complete&&i.naturalWidth>0&&i.naturalWidth<=480))).toBe(true)
  const memory=await app.evaluate(({app,BrowserWindow})=>app.getAppMetrics().find(process=>process.pid===BrowserWindow.getAllWindows()[0].webContents.getOSProcessId()).memory);assert((memory.workingSetSize)<700*1024)
  await page.locator('.results-modal .ant-modal-close').click();return {frames:999,maxDOMPerPage:count,thumbnailMaxWidth:480,originalWidth:3840,rendererMemoryKiB:memory}
 })
 await test('30分钟视频结果恢复、末页和跳转',async()=>{
  await pick(pressure.cases[1].job.folder);await page.evaluate(()=>window.framepick.importResults());await waitState(s=>s.jobs.length===2);const job=(await snapshot()).jobs.find(j=>j.name.includes('30分钟'));await page.locator(`[data-job-id="${job.id}"]`).getByRole('button',{name:'查看图片',exact:true}).click();await expect(page.locator('.results-toolbar>span')).toContainText('899');const result=await page.evaluate(id=>window.framepick.results(id,14),job.id);assert.equal(result.frames.length,59);assert.equal(result.frames.at(-1).target,1798);await page.locator('.results-modal .ant-modal-close').click();return {sourceSeconds:1800,frames:899,lastSeconds:1798}
 })
 await test('100个项目与500个素材条目的搜索、分类和界面响应',async()=>{
  const source=pressure.cases[0].source,manifest=JSON.parse(fs.readFileSync(pressure.cases[0].job.manifest,'utf8')),workspace=await snapshot();workspace.videos=Array.from({length:500},(_,index)=>({id:'stress-video-'+index,projectId:'stress-project-'+Math.floor(index/5),name:'压力素材 '+String(index).padStart(4,'0'),source:'local',path:source,info:manifest.info,status:'ready'}));workspace.projects=Array.from({length:100},(_,index)=>({id:'stress-project-'+index,name:'压力项目 '+index,collapsed:false}));workspace.jobs=[]
  const file=path.join(artifact,'500素材备份.json');fs.writeFileSync(file,JSON.stringify({application:'Framepick',version:1,workspace,drafts:{}}));await pick(file);const start=Date.now();await page.evaluate(()=>window.framepick.importWorkspace());await waitState(s=>s.videos.length===500&&s.projects.length===100);await page.getByRole('button',{name:'抽帧工作台',exact:true}).click();await expect(page.locator('.video-row')).toHaveCount(500);const renderSeconds=(Date.now()-start)/1000
  await page.getByRole('textbox',{name:'搜索视频',exact:true}).fill('压力素材 0499');await expect(page.locator('.video-row')).toHaveCount(1);await page.getByRole('textbox',{name:'搜索视频',exact:true}).fill('');await expect(page.locator('.video-row')).toHaveCount(500)
  const state=await snapshot();await page.evaluate(async values=>{await window.framepick.moveVideos([values.video],values.project);await window.framepick.pinVideo(values.video,true)}, {video:state.videos[499].id,project:state.projects[0].id});await waitState(s=>s.videos[499].projectId===s.projects[0].id&&!!s.videos[499].pinnedAt);const memory=await app.evaluate(({app,BrowserWindow})=>app.getAppMetrics().find(process=>process.pid===BrowserWindow.getAllWindows()[0].webContents.getOSProcessId()).memory);assert(errors.length===0);return {projects:100,entries:500,sharedSource:true,initialRenderSeconds:renderSeconds,rendererMemoryKiB:memory}
 })
 console.log(JSON.stringify({result:'passed',artifact,cases:cases.length}))
}catch(error){console.error(error);process.exitCode=1}finally{if(app)await app.close()}})()
