const {_electron:electron,expect}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto')
const root=path.resolve(__dirname,'..'),version=require('../package.json').version,source=process.env.FRAMEPICK_TEST_VIDEO,url=process.env.FRAMEPICK_TEST_URL
if(!source||!fs.existsSync(source))throw new Error('Set FRAMEPICK_TEST_VIDEO to an existing video.')
const artifact=path.join(root,'.test-artifacts',version,'ux-workflows',String(Date.now())),data=path.join(artifact,'user-data'),output=path.join(artifact,'output'),downloads=path.join(artifact,'downloads')
fs.mkdirSync(output,{recursive:true});fs.mkdirSync(downloads,{recursive:true})
const a=path.join(artifact,'示例A.mp4'),b=path.join(artifact,'示例B.mp4'),c=path.join(artifact,'示例C.mp4');for(const f of [a,b,c])fs.copyFileSync(source,f)
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),originalHash=hash(source),cases=[],errors=[]
let app,page,va,vb,vc,resultJob,online
const snap=()=>page.evaluate(()=>window.framepick.snapshot()),wait=fn=>expect.poll(async()=>fn(await snap()),{timeout:240000}).toBe(true)
const report=()=>fs.writeFileSync(path.join(artifact,'report.json'),JSON.stringify({version,packaged:!!process.env.FRAMEPICK_PACKAGED_EXE,cases,errors,originalUnchanged:hash(source)===originalHash},null,2))
async function test(name,fn){try{const evidence=await fn();cases.push({name,status:'passed',evidence});console.log('PASS '+name)}catch(e){cases.push({name,status:'failed',error:e.message});await page?.screenshot({path:path.join(artifact,'failed.png')}).catch(()=>{});throw e}finally{report()}}
async function launch(){app=await electron.launch({executablePath:process.env.FRAMEPICK_PACKAGED_EXE||require('electron'),args:process.env.FRAMEPICK_PACKAGED_EXE?['--hidden']:[root,'--hidden'],env:{...process.env,FRAMEPICK_TEST_DATA:data,ELECTRON_RENDERER_URL:''},timeout:60000});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);await wait(s=>s.health.ready);await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.show();w.focus()});await page.emulateMedia({reducedMotion:'reduce'});await app.evaluate(({dialog},folders)=>{global.fpDialog=dialog.showOpenDialog;global.fpCancelDownload=false;dialog.showOpenDialog=async(...args)=>{const o=args.at(-1);if(/下载/.test(o.title))return {canceled:global.fpCancelDownload,filePaths:global.fpCancelDownload?[]:[folders.downloads]};if(/根目录|剪切/.test(o.title))return {canceled:false,filePaths:[folders.output]};return global.fpDialog(...args)}},{downloads,output})}
async function time(label,value){const input=page.getByRole('textbox',{name:label,exact:true});await input.fill(value);await input.press('Tab')}
async function focus(v){await page.locator(`[data-video-id="${v.id}"]`).click()}
async function operation(name){await page.getByRole('button',{name:'视频操作 ▾',exact:true}).click();await page.getByRole('menuitem',{name,exact:true}).click()}
async function drag(label,mode,fraction,release=true){const target=page.getByRole('slider',{name:`${label}${mode}`,exact:true}),h=await target.boundingBox(),track=await page.locator(`[data-timeline="${label}"]`).boundingBox();await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();await page.mouse.move(track.x+track.width*fraction,h.y+h.height/2,{steps:12});if(release)await page.mouse.up()}
async function screenshot(name){await page.evaluate(names=>{window.fpRedacted=[];const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const n=walker.currentNode;let text=n.textContent;for(const original of names)if(original)text=text.split(original).join('示例视频');if(text!==n.textContent){window.fpRedacted.push([n,n.textContent]);n.textContent=text}}},(await snap()).videos.map(v=>v.name));try{await page.addStyleTag({content:'.video-title-bar p,.folder-picker span,.download-summary span,.delete-file-list small,.ant-tooltip{visibility:hidden!important}'});await page.mouse.move(2,2);await app.evaluate(async({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];await w.webContents.capturePage();await new Promise(r=>setTimeout(r,300));await w.webContents.capturePage()});await page.screenshot({path:path.join(artifact,name+'.png')})}finally{await page.evaluate(()=>{for(const [node,text] of window.fpRedacted)node.textContent=text;delete window.fpRedacted})}}
;(async()=>{try{
 await launch()
 await test('批量导入不勾选，最新视频自动预览且范围完整',async()=>{await page.evaluate(files=>window.framepick.addFiles(files),[a,b]);await wait(s=>s.videos.length===2&&s.videos.every(v=>v.status==='ready'));[va,vb]=(await snap()).videos;await expect(page.locator('.video-row input:checked')).toHaveCount(0);await expect(page.locator(`[data-video-id="${vb.id}"]`)).toHaveClass(/focused/);assert.deepEqual(vb.extractRange,{start:0,end:null});await expect(page.getByRole('slider',{name:'截取终点拖动柄',exact:true})).toHaveAttribute('aria-valuenow',String(Math.round(vb.info.duration*1000)/1000));await expect.poll(()=>page.locator('.preview-stage video').evaluate(v=>{v.muted=true;return v.readyState})).toBeGreaterThanOrEqual(2);await screenshot('workbench-0.7.1');return {unchecked:true,latestPreview:true,fullDuration:true}})
 await test('每个视频单独保存范围，共用参数不会覆盖范围',async()=>{await focus(va);await time('开始时间','00:01.000');await time('结束时间','00:03.000');await focus(vb);await expect(page.getByRole('textbox',{name:'开始时间',exact:true})).toHaveValue('00:00.000');await time('开始时间','00:04.000');await time('结束时间','00:06.000');await page.getByRole('button',{name:'0.5 秒',exact:true}).click();await focus(va);await expect(page.getByRole('textbox',{name:'开始时间',exact:true})).toHaveValue('00:01.000');await expect(page.getByRole('textbox',{name:'结束时间',exact:true})).toHaveValue('00:03.000');assert.deepEqual((await snap()).videos[1].extractRange,{start:4,end:6});return {independent:true,sharedInterval:true}})
 await test('新增素材不继承短选区、不改变已有批量勾选',async()=>{await page.locator(`[data-video-id="${va.id}"] input`).check();await page.evaluate(file=>window.framepick.addFiles([file]),c);await wait(s=>s.videos.length===3&&s.videos[2].status==='ready');vc=(await snap()).videos[2];await expect(page.locator('.video-row input:checked')).toHaveCount(1);await expect(page.locator(`[data-video-id="${vc.id}"] input`)).not.toBeChecked();assert.deepEqual(vc.extractRange,{start:0,end:null});return {existingSelectionPreserved:true,newUnchecked:true,newFullRange:true}})
 await test('统一范围需要明确应用，取消时不改变其他视频',async()=>{await page.locator(`[data-video-id="${vb.id}"] input`).check();await time('开始时间','00:00.500');await time('结束时间','00:02.500');await page.getByRole('button',{name:'应用到已选视频（2）',exact:true}).click();await page.locator('.ant-modal-confirm').getByRole('button',{name:/^取\s*消$/}).click();assert.deepEqual((await snap()).videos[0].extractRange,{start:1,end:3});await page.getByRole('button',{name:'应用到已选视频（2）',exact:true}).click();await page.getByRole('button',{name:'应用范围',exact:true}).click();await wait(s=>s.videos.slice(0,2).every(v=>v.extractRange.start===.5&&v.extractRange.end===2.5));return {explicitApply:true,cancelSafe:true}})
 await test('抽帧当前视频忽略其他勾选，仅产生一个任务',async()=>{await page.evaluate(async id=>{await window.framepick.chooseOutput();const s=await window.framepick.snapshot();await window.framepick.saveSettings({...s.settings,interval:.5,includeStart:true,format:'png',maxWidth:360,conflict:'batch',autoStitch:false});await window.framepick.setExtractRanges([id],{start:0,end:3})},vc.id);const before=(await snap()).jobs.length;await page.getByRole('button',{name:'抽帧当前视频',exact:true}).click();await wait(s=>s.jobs.length===before+1&&s.jobs.at(-1).status==='done');resultJob=(await snap()).jobs.at(-1);assert.equal(resultJob.videoId,vc.id);assert.equal(resultJob.count,6);return {oneTask:true,ignoredOtherChecks:true,frames:6}})
 await test('批量抽帧只处理勾选素材，不包含正在预览的视频',async()=>{const before=(await snap()).jobs.length;await page.getByRole('button',{name:'批量抽帧（已选 2 个）',exact:true}).click();await wait(s=>s.jobs.length===before+2&&s.jobs.slice(before).every(j=>j.status==='done'));assert.deepEqual((await snap()).jobs.slice(before).map(j=>j.videoId),[va.id,vb.id]);return {twoCheckedTasks:true,previewExcluded:true}})
 await test('绿色手柄拖动即时更新，松开后保存并同步真实画面',async()=>{await page.evaluate(id=>window.framepick.setExtractRanges([id],{start:1,end:8}),vc.id);await drag('截取','起点拖动柄',.08,false);const displayed=Number(await page.getByRole('slider',{name:'截取起点拖动柄',exact:true}).getAttribute('aria-valuenow'));assert(displayed>2);assert.equal((await snap()).videos[2].extractRange.start,1);await expect.poll(()=>page.locator('.preview-stage video').evaluate(v=>v.currentTime)).toBeCloseTo(displayed,1);await page.mouse.up();await wait(s=>Math.abs(s.videos[2].extractRange.start-displayed)<.002);await drag('截取','终点拖动柄',.24);const saved=(await snap()).videos[2].extractRange;await expect.poll(()=>page.locator('.preview-stage video').evaluate(v=>v.currentTime)).toBeCloseTo(saved.end,1);return {instantVisual:true,commitOnRelease:true,realFrameSynced:true}})
 await test('黄色播放线不修改范围，绿色色块整体移动范围',async()=>{const before={...(await snap()).videos[2].extractRange};await drag('截取','播放进度',.4);assert.deepEqual((await snap()).videos[2].extractRange,before);const selection=page.locator('[data-timeline="截取"] .timeline-selection'),h=await selection.boundingBox();await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();await page.mouse.move(h.x+h.width/2+30,h.y+h.height/2,{steps:10});await page.mouse.up();await wait(s=>s.videos[2].extractRange.start>before.start);const after=(await snap()).videos[2].extractRange;assert(Math.abs(after.end-after.start-(before.end-before.start))<.003);return {playheadIndependent:true,spanPreserved:true}})
 await test('窄选区手柄可分别点中，播放线贴合轨道，时间轴可放大还原',async()=>{
  await page.evaluate(id=>window.framepick.setExtractRanges([id],{start:10,end:10.05}),vc.id);await expect(page.locator('[data-timeline="截取"]')).toHaveClass(/handles-close/)
  const positions=await page.locator('[data-timeline="截取"]').evaluate(el=>{const rail=el.querySelector('.timeline-rail').getBoundingClientRect();return ['start','end','seek'].map(mode=>{const b=el.querySelector(`[data-timeline-handle="${mode}"]`),r=b.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2),line=getComputedStyle(b,mode==='seek'?'::after':'::before'),top=r.y+parseFloat(line.top);return {mode,hit:hit?.dataset.timelineHandle,top,bottom:top+parseFloat(line.height),railTop:rail.top,railBottom:rail.bottom}})});for(const p of positions){assert.equal(p.hit,p.mode);assert(p.top<=p.railTop&&p.bottom>=p.railBottom)}
  await page.getByRole('button',{name:'截取放大时间轴',exact:true}).click();assert(await page.locator('[data-timeline="截取"]').evaluate(el=>el.offsetWidth>el.parentElement.clientWidth));await page.getByRole('button',{name:'截取完整时间轴',exact:true}).click();await page.evaluate(id=>window.framepick.setExtractRanges([id],{start:0,end:3}),vc.id);await screenshot('independent-range-0.7.1');return {separateHitTargets:true,indicatorsOnRail:true,zoom:true,restore:true}
 })
 await test('常规与紧凑窗口时间轴布局核对，无控件越界或标签拆散',async()=>{
  const original=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].getSize()),measured=[];for(const size of [[1440,920],[1280,720],[1024,700]]){await app.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setSize(...size),size);await page.waitForTimeout(250);measured.push(await page.evaluate(()=>({width:innerWidth,height:innerHeight})));await page.locator('[data-timeline="截取"]').scrollIntoViewIfNeeded();const layout=await page.locator('.workspace-timeline').evaluate(el=>{const outer=el.getBoundingClientRect();return [...el.querySelectorAll('.timeline-controls button,.timeline-range-group,.timeline-caption .ant-select')].map(e=>{const r=e.getBoundingClientRect();return r.left>=outer.left-1&&r.right<=outer.right+1})});assert(layout.every(Boolean));await screenshot(`timeline-layout-${size[0]}-0.7.1`)}await app.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setSize(...size),original);return {requestedWindowWidths:[1440,1280,1024],measuredViewportSizes:measured,containedControls:true,groupedRangeFields:true}
 })
 await test('毫秒输入与换算、校验及裁剪窗口共用输入模式',async()=>{await page.getByLabel('时间输入方式',{exact:true}).click();await page.getByText('毫秒 · 65000 ms',{exact:true}).last().click();await time('开始时间','1000');await time('结束时间','3500');assert.deepEqual((await snap()).videos[2].extractRange,{start:1,end:3.5});await expect(page.getByRole('textbox',{name:'开始时间',exact:true})).toHaveValue('1000');await expect(page.locator('.settings-panel .time-converted').first()).toHaveText('= 00:01.000');await time('开始时间','1.5');await expect(page.getByRole('textbox',{name:'开始时间',exact:true})).toHaveAttribute('aria-invalid','true');await time('开始时间','1000');await operation('裁剪画面');await expect(page.getByRole('textbox',{name:'裁剪播放位置',exact:true})).toHaveValue('0');await expect(page.getByRole('slider',{name:'裁剪终点拖动柄',exact:true})).toHaveAttribute('aria-valuenow',String(Math.round(vc.info.duration*1000)/1000));await page.getByRole('button',{name:/^取\s*消$/}).last().click();await page.getByLabel('时间输入方式',{exact:true}).click();await page.getByText('时分秒 · 01:05.000',{exact:true}).last().click();await expect(page.getByRole('textbox',{name:'开始时间',exact:true})).toHaveValue('00:01.000');return {milliseconds:true,conversion:true,invalidRejected:true,cropFullRange:true,modeShared:true}})
 await test('部分删除同步清理备注、配方与索引，保留其他结果',async()=>{const info=await page.evaluate(id=>window.framepick.results(id,0),resultJob.id),first=info.frames[0].name,last=info.frames.at(-1).name;await page.evaluate(async({id,first,last})=>{const s=await window.framepick.snapshot(),value={...s.settings,rows:2,columns:3,perSheet:6,notesEnabled:true,frameOrder:[first,last],markerPositions:{[first]:{x:.1,y:.1}}};await window.framepick.saveStitchDraft(id,{[first]:'需要删除的备注',[last]:'保留的备注'},value);await window.framepick.stitch(id,[],value,{page:0})},{id:resultJob.id,first,last});await page.getByRole('button',{name:'查看导出图片',exact:true}).click();await page.locator('.results-grid input').first().check();await page.getByRole('button',{name:'删除所选图片文件',exact:true}).click();await page.getByLabel('我已核对以上文件，确认要删除磁盘上的文件',{exact:true}).check();await page.getByRole('button',{name:'真正删除 1 个文件',exact:true}).click();await expect(page.getByText('删除磁盘文件',{exact:true})).not.toBeVisible();const result=await page.evaluate(id=>window.framepick.results(id,0),resultJob.id),manifest=JSON.parse(fs.readFileSync(resultJob.manifest,'utf8')),registry=JSON.parse(fs.readFileSync(path.join(resultJob.folder,'.framepick-frames.json'),'utf8'));assert.equal(result.total,5);assert.equal(result.missing,0);assert(!manifest.notes[first]);assert.equal(manifest.notes[last],'保留的备注');assert(!registry.frames[first]);assert(Object.values(manifest.sheetRecipes).every(r=>!r.names.includes(first)&&!r.notes[first]));await page.locator('.results-modal .ant-modal-close').click();return {frameRemoved:true,noteRemoved:true,registryClean:true,recipeClean:true,otherResultsPreserved:true}})
 await test('删除失败保留文件及记录，成功项仍同步清理',async()=>{const info=await page.evaluate(id=>window.framepick.results(id,0),resultJob.id),failed=info.frames[0];await app.evaluate(({shell},file)=>{global.fpTrash=shell.trashItem;shell.trashItem=async p=>{if(p===file)throw new Error('test locked');return global.fpTrash(p)}},failed.path);const result=await page.evaluate(async id=>{const p=await window.framepick.planDelete({jobId:id});return window.framepick.deleteFiles(p.token,p.files.map(f=>f.id))},resultJob.id);await app.evaluate(({shell})=>shell.trashItem=global.fpTrash);assert(result.errors.length&&result.removedJobIds.length===0);assert(fs.existsSync(failed.path));const retained=await page.evaluate(id=>window.framepick.results(id,0),resultJob.id);assert.equal(retained.total,1);assert.equal(retained.frames[0].name,failed.name);return {failurePreserved:true,successCleaned:true,errorReported:true}})
 await test('全部结果删除后关闭窗口、移除任务，原视频与其他文件保留',async()=>{const unrelated=path.join(resultJob.folder,'用户其他文件.txt');fs.writeFileSync(unrelated,'keep');await page.getByRole('button',{name:'查看导出图片',exact:true}).click();await page.getByRole('button',{name:'删除导出文件',exact:true}).click();await page.getByLabel('我已核对以上文件，确认要删除磁盘上的文件',{exact:true}).check();await page.getByRole('button',{name:'真正删除 1 个文件',exact:true}).click();await expect(page.locator('.results-modal')).not.toBeVisible();assert(!(await snap()).jobs.some(j=>j.id===resultJob.id));assert(!fs.existsSync(resultJob.manifest));assert(!fs.existsSync(path.join(resultJob.folder,'.framepick-frames.json')));assert(fs.existsSync(unrelated)&&hash(source)===originalHash);return {taskRemoved:true,manifestRemoved:true,indexRemoved:true,windowClosed:true,unrelatedPreserved:true,originalUnchanged:true}})
 await test('删除最后一页后自动返回有效页，编辑器刷新且不复活旧备注',async()=>{
  await page.evaluate(async id=>{const s=await window.framepick.snapshot();await window.framepick.saveSettings({...s.settings,interval:.1,includeStart:true,autoStitch:false});await window.framepick.setExtractRanges([id],{start:0,end:6.5});await window.framepick.enqueue([id])},vc.id);await wait(s=>s.jobs.at(-1).status==='done');const job=(await snap()).jobs.at(-1);assert.equal(job.count,65)
  await page.getByRole('button',{name:'查看导出图片',exact:true}).click();await page.locator('.results-modal .ant-pagination:visible').getByTitle('2',{exact:true}).click();await expect(page.locator('.results-grid input')).toHaveCount(5);const names=(await page.evaluate(id=>window.framepick.results(id,1),job.id)).frames.map(f=>f.name);await page.getByLabel('选择本页',{exact:true}).check();await page.getByRole('button',{name:'删除所选图片文件',exact:true}).click();await page.getByLabel('我已核对以上文件，确认要删除磁盘上的文件',{exact:true}).check();await page.getByRole('button',{name:'真正删除 5 个文件',exact:true}).click();await expect.poll(()=>page.locator('.results-grid input').count()).toBeGreaterThan(5);await expect(page.locator('.results-modal .ant-pagination-item-active:visible')).toHaveText('1')
  await page.getByRole('tab',{name:'拼接编辑',exact:true}).click();await expect(page.locator('.story-cell[data-frame]').first()).toBeVisible();await page.waitForTimeout(800);const manifest=JSON.parse(fs.readFileSync(job.manifest,'utf8'));assert.equal(manifest.frames.length,60);assert(names.every(n=>!manifest.notes[n]&&!manifest.stitchDraft.frameOrder.includes(n)));const result=await page.evaluate(id=>window.framepick.results(id,99),job.id);assert.equal(result.page,0);assert.equal(result.frames.length,60);await page.locator('.results-modal .ant-modal-close').click();return {pageClamped:true,editorRefreshed:true,deletedReferencesAbsent:true}
 })
 await test('范围应用边界检查，无效批量操作不产生部分修改',async()=>{await page.evaluate(id=>window.framepick.setExtractRanges([id],{start:1,end:999}),va.id);assert.equal((await snap()).videos[0].extractRange.end,va.info.duration);const before=(await snap()).videos.map(v=>v.extractRange);const error=await page.evaluate(async ids=>{try{await window.framepick.setExtractRanges(ids,{start:999,end:null});return ''}catch(e){return e.message}},[va.id,vb.id]);assert(error.includes('起点超出'));assert.deepEqual((await snap()).videos.map(v=>v.extractRange),before);return {endClamped:true,atomicValidation:true}})
 await test('共享图片及归档任务同步清理，恢复归档不会复活删除结果',async()=>{const file=path.join(artifact,'共享结果.mp4');fs.copyFileSync(source,file);await page.evaluate(f=>window.framepick.addFiles([f]),file);await wait(s=>s.videos.at(-1).status==='ready');const id=(await snap()).videos.at(-1).id;await page.evaluate(async id=>{const s=await window.framepick.snapshot();await window.framepick.saveSettings({...s.settings,conflict:'skip',interval:1,includeStart:true,autoStitch:false});await window.framepick.setExtractRanges([id],{start:0,end:2});await window.framepick.enqueue([id])},id);await wait(s=>s.jobs.at(-1).status==='done');const first=(await snap()).jobs.at(-1);await page.evaluate(id=>window.framepick.archiveJobs([id]),first.id);await page.evaluate(id=>window.framepick.enqueue([id]),id);await wait(s=>s.jobs.at(-1).status==='done');const second=(await snap()).jobs.at(-1);assert.equal(first.folder,second.folder);const frames=await page.evaluate(id=>window.framepick.results(id,0),second.id);await page.evaluate(async({id,name})=>{const p=await window.framepick.planDelete({jobId:id,names:[name]});await window.framepick.deleteFiles(p.token,p.files.map(f=>f.id))},{id:second.id,name:frames.frames[0].name});assert.equal(JSON.parse(fs.readFileSync(first.manifest,'utf8')).frames.length,1);assert.equal(JSON.parse(fs.readFileSync(second.manifest,'utf8')).frames.length,1);const result=await page.evaluate(async id=>{const p=await window.framepick.planDelete({jobId:id});return window.framepick.deleteFiles(p.token,p.files.map(f=>f.id))},second.id);assert(result.removedJobIds.includes(first.id)&&result.removedJobIds.includes(second.id));await page.evaluate(()=>window.framepick.restoreArchives());assert(!(await snap()).jobs.some(j=>[first.id,second.id].includes(j.id)));return {sharedRecordsCleaned:true,archiveCleaned:true,noDeletedResultRestoration:true}})
 if(url){
 await test('取消下载文件夹不解析、不新增视频或任务',async()=>{await app.evaluate(()=>global.fpCancelDownload=true);const before=await snap();await page.getByRole('button',{name:'粘贴视频链接',exact:true}).click();await page.getByRole('textbox',{name:'在线视频链接',exact:true}).fill(url);await page.locator('.ant-modal:visible .ant-modal-footer .ant-btn-primary').click();await expect(page.locator('.ant-modal:visible .ant-modal-footer .ant-btn-primary')).not.toHaveClass(/ant-btn-loading/,{timeout:20000});assert.equal((await snap()).videos.length,before.videos.length);assert.equal((await snap()).jobs.length,before.jobs.length);await page.locator('.ant-modal').getByRole('button',{name:/^取\s*消$/}).last().click();await app.evaluate(()=>global.fpCancelDownload=false);return {noMutation:true,noDownload:true}})
 await test('实际在线视频解析自动下载至选择位置，直接播放且不生成预览缓存',async()=>{await page.getByRole('button',{name:'粘贴视频链接',exact:true}).click();await page.getByRole('textbox',{name:'在线视频链接',exact:true}).fill(url);await page.locator('.ant-modal:visible .ant-modal-footer .ant-btn-primary').click();await expect(page.getByRole('textbox',{name:'在线视频链接',exact:true})).not.toBeVisible({timeout:240000});await wait(s=>s.videos.some(v=>v.source==='online')&&!s.jobs.some(j=>j.kind==='download'&&['waiting','running'].includes(j.status)));online=(await snap()).videos.find(v=>v.source==='online');if(!online.downloadedPath){const job=(await snap()).jobs.find(j=>j.kind==='download');await page.evaluate(id=>window.framepick.retryJob(id),job.id);await wait(s=>!s.jobs.some(j=>j.kind==='download'&&['waiting','running'].includes(j.status)));online=(await snap()).videos.find(v=>v.id===online.id)}assert(online.downloadedPath,online.downloadError);assert.equal(path.dirname(online.downloadedPath),downloads);assert.equal(online.localReady,true);assert(!online.previewPath);assert(!fs.existsSync(path.join(data,'cache','playback')));assert(!fs.existsSync(path.join(data,'cache','downloads')));assert(!fs.readdirSync(downloads).some(n=>n.startsWith('.framepick-download-')));await expect(page.locator(`[data-video-id="${online.id}"] input`)).not.toBeChecked();await expect.poll(()=>page.locator('.preview-stage video').evaluate(v=>{v.muted=true;return v.readyState}),{timeout:60000}).toBeGreaterThanOrEqual(2);await time('截取播放位置','00:03.000');await page.getByRole('button',{name:'截取播放',exact:true}).click();await expect.poll(()=>page.locator('.preview-stage video').evaluate(v=>v.currentTime)).toBeGreaterThan(3.3);await page.getByRole('button',{name:'截取暂停',exact:true}).click();await screenshot('download-first-0.7.1');return {anonymous:true,userFolder:true,nativePlayback:true,noAutoConversion:true,codec:online.info.codec,quality:online.info.height}})
 await test('同一链接复用已下载视频，不重复创建任务或文件',async()=>{const before=await snap(),files=fs.readdirSync(downloads);const result=await page.evaluate(text=>window.framepick.resolveLinks(text),url);assert.equal(result.queued,0);assert.equal(result.reused,1);assert.equal((await snap()).jobs.length,before.jobs.length);assert.deepEqual(fs.readdirSync(downloads),files);return {reused:true,noDuplicateTask:true,noDuplicateFile:true}})
 await test('在线视频抽帧复用保存文件，源文件缺失时禁止偷偷下载',async()=>{const savedHash=hash(online.downloadedPath);await page.evaluate(async id=>{const s=await window.framepick.snapshot();await window.framepick.saveSettings({...s.settings,interval:1,includeStart:true,autoStitch:false});await window.framepick.setExtractRanges([id],{start:0,end:3});await window.framepick.enqueue([id])},online.id);await wait(s=>s.jobs.at(-1)?.status==='done');assert.equal((await snap()).jobs.at(-1).count,3);const moved=online.downloadedPath+'.test-moved';fs.renameSync(online.downloadedPath,moved);try{const result=await page.evaluate(async id=>{try{await window.framepick.enqueue([id]);return ''}catch(e){return e.message}},online.id);assert(result.includes('不会自动重新下载'));const preview=await page.evaluate(async id=>{try{await window.framepick.preparePreview(id,true);return ''}catch(e){return e.message}},online.id);assert(preview.includes('不会自动重新下载'));assert(!fs.existsSync(online.downloadedPath))}finally{fs.renameSync(moved,online.downloadedPath)}assert.equal(hash(online.downloadedPath),savedHash);return {savedFileReused:true,threeFrames:true,missingFileBlocked:true,sourceUnchanged:true}})
 }
 await test('播放失败不自动转码，只有手动兼容预览才生成副本',async()=>{await focus(vc);const videoBefore=(await snap()).videos.find(v=>v.id===vc.id),before=hash(vc.path);assert(!videoBefore.previewPath);await page.locator('.preview-stage video').evaluate(v=>v.dispatchEvent(new Event('error')));await expect(page.getByRole('button',{name:'生成兼容预览（可选）',exact:true})).toBeVisible();assert(!(await snap()).videos.find(v=>v.id===vc.id).previewStatus);await page.getByRole('button',{name:'生成兼容预览（可选）',exact:true}).click();await wait(s=>s.videos.find(v=>v.id===vc.id)?.previewStatus==='ready');const v=(await snap()).videos.find(v=>v.id===vc.id);assert(v.previewPath&&v.previewPath!==v.path&&v.previewSource===v.path);assert.equal(hash(vc.path),before);await expect.poll(()=>page.locator('.preview-stage video').evaluate(v=>v.readyState),{timeout:30000}).toBeGreaterThanOrEqual(2);await page.evaluate(async id=>{await window.framepick.setExtractRanges([id],{start:0,end:1});await window.framepick.enqueue([id])},vc.id);await wait(s=>s.jobs.at(-1).status==='done');const manifest=JSON.parse(fs.readFileSync((await snap()).jobs.at(-1).manifest,'utf8'));assert.equal(manifest.sourcePath,vc.path);return {noAutoConversion:true,manualConversion:true,originalUnchanged:true,extractionUsesOriginal:true}})
 await test('重启保留各视频范围和毫秒模式，不自动勾选素材',async()=>{await page.evaluate(()=>window.framepick.saveTimeInputMode('milliseconds'));const ranges=(await snap()).videos.map(v=>v.extractRange);await app.close();app=null;await launch();assert.deepEqual((await snap()).videos.map(v=>v.extractRange),ranges);assert.equal((await snap()).timeInputMode,'milliseconds');await expect(page.locator('.video-row input:checked')).toHaveCount(0);assert.equal(errors.length,0);assert.equal(hash(source),originalHash);return {rangePersistence:true,modePersistence:true,uncheckedAfterRestart:true,rendererErrors:0,sourceUnchanged:true}})
 console.log(JSON.stringify({result:'passed',cases:cases.length,artifact}))
}finally{report();if(app)await app.close().catch(()=>{})}})().catch(e=>{console.error(e);process.exitCode=1})
