const {_electron:electron,expect}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto')
const root=path.resolve(__dirname,'..'),version=require('../package.json').version,source=process.env.FRAMEPICK_TEST_VIDEO,url=process.env.FRAMEPICK_TEST_URL
if(!source||!fs.existsSync(source))throw new Error('Set FRAMEPICK_TEST_VIDEO to an existing video.')
const artifact=path.join(root,'.test-artifacts',version,'video-workflows',String(Date.now())),output=path.join(artifact,'output'),data=path.join(artifact,'user-data')
fs.mkdirSync(output,{recursive:true});const cases=[],errors=[],hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),originalHash=hash(source)
let app,page,original,job,splitFiles=[],joinedFile,online
const snap=()=>page.evaluate(()=>window.framepick.snapshot()),wait=fn=>expect.poll(async()=>fn(await snap()),{timeout:240000}).toBe(true)
async function screenshot(name){if(!process.env.FRAMEPICK_PACKAGED_EXE)return;await page.evaluate(names=>{const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);window.fpRedacted=[];while(walker.nextNode()){const node=walker.currentNode;let next=node.textContent;for(const [i,name] of names.entries())if(name)next=next.split(name).join('示例视频 '+(i+1));if(next!==node.textContent){window.fpRedacted.push([node,node.textContent]);node.textContent=next}}},(await snap()).videos.map(v=>v.name));try{await page.mouse.move(4,4);await page.screenshot({path:path.join(artifact,name+'.png'),style:'.video-title-bar p,.folder-picker span,.download-summary span,.delete-file-list small,.ant-tooltip{visibility:hidden!important}'})}finally{await page.evaluate(()=>{for(const [node,text] of window.fpRedacted)node.textContent=text;delete window.fpRedacted})}}
const report=()=>fs.writeFileSync(path.join(artifact,'report.json'),JSON.stringify({version,packaged:!!process.env.FRAMEPICK_PACKAGED_EXE,cases,errors,originalUnchanged:hash(source)===originalHash},null,2))
async function test(name,fn){try{const evidence=await fn();cases.push({name,status:'passed',evidence});console.log('PASS '+name)}catch(e){cases.push({name,status:'failed',error:e.message});if(page&&!page.isClosed())await page.screenshot({path:path.join(artifact,'failed.png'),timeout:10000}).catch(()=>{});throw e}finally{report()}}
async function operation(name){await page.getByRole('button',{name:'视频操作 ▾',exact:true}).click();await page.getByRole('menuitem',{name,exact:true}).click()}
async function time(label,value,scope=page){const input=scope.getByRole('textbox',{name:label,exact:true});await input.fill(value);await input.press('Tab')}
async function seek(label,fraction){const track=page.locator(`[data-timeline="${label}"]`),box=await track.boundingBox(),head=page.getByRole('slider',{name:`${label}播放进度`,exact:true}),h=await head.boundingBox();await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width*fraction,box.y+15,{steps:8});await page.mouse.up()}
async function launch(){app=await electron.launch({executablePath:process.env.FRAMEPICK_PACKAGED_EXE||require('electron'),args:process.env.FRAMEPICK_PACKAGED_EXE?['--hidden']:[root,'--hidden'],env:{...process.env,FRAMEPICK_TEST_DATA:data,ELECTRON_RENDERER_URL:''},timeout:60000});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await wait(s=>s.health.ready);await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.show();w.focus()});await page.emulateMedia({reducedMotion:'reduce'});await page.addStyleTag({content:'.video-title-bar p,.folder-picker span{visibility:hidden}'});await app.evaluate(({dialog},folder)=>{global.fpOutput=folder;global.fpDialog=dialog.showOpenDialog;dialog.showOpenDialog=async(...args)=>{const options=args.at(-1);if(/剪切|下载|根目录/.test(options.title||''))return {canceled:false,filePaths:[folder]};return global.fpDialog(...args)}},output)}
;(async()=>{try{
 await launch()
 await test('真实本地视频导入、视频画面解码与播放',async()=>{await page.evaluate(file=>window.framepick.addFiles([file]),source);await wait(s=>s.videos[0]?.status==='ready');original=(await snap()).videos[0];await expect.poll(()=>page.locator('.preview-stage video').evaluate(v=>{v.muted=true;return v.readyState})).toBeGreaterThanOrEqual(2);await page.getByRole('button',{name:'截取播放',exact:true}).click();await expect.poll(()=>page.locator('.preview-stage video').evaluate(v=>v.currentTime)).toBeGreaterThan(.3);await page.getByRole('button',{name:'截取暂停',exact:true}).click();return {decoded:true,playing:true}})
 await test('下拉操作菜单、默认关闭剪切与默认展开时间轴',async()=>{assert(!original.trimEnabled);await expect(page.locator('[data-timeline="截取"]')).toBeVisible();await page.getByRole('button',{name:'视频操作 ▾',exact:true}).click();await expect(page.getByRole('menuitem',{name:'剪切长度',exact:true})).toHaveCount(0);await expect(page.getByRole('checkbox',{name:'启用视频剪切',exact:true})).not.toBeChecked();await screenshot('video-menu-0.7.0');await page.keyboard.press('Escape');await page.getByRole('button',{name:'截取范围 · 可视化时间轴'}).click();await expect(page.locator('[data-timeline="截取"]')).not.toBeVisible();await page.getByRole('button',{name:'截取范围 · 可视化时间轴'}).click();await expect(page.locator('[data-timeline="截取"]')).toBeVisible();return {trimOffByDefault:true,dropdown:true,timelineExpanded:true,collapsible:true}})
 await test('时分秒输入、毫秒范围和无效时间提示',async()=>{await time('开始时间','00:02.500');await time('结束时间','00:05.250');assert.equal((await snap()).videos[0].extractRange.start,2.5);assert.equal((await snap()).videos[0].extractRange.end,5.25);await expect(page.getByRole('textbox',{name:'开始时间',exact:true})).toHaveValue('00:02.500');const input=page.getByRole('textbox',{name:'开始时间',exact:true});await input.fill('00:90.000');await input.press('Tab');await expect(input).toHaveAttribute('aria-invalid','true');assert.equal((await snap()).videos[0].extractRange.start,2.5);await time('开始时间','00:02.500');return {formatted:true,milliseconds:true,invalidRejected:true}})
 await test('截取时间轴拖动同步真实播放位置和画面',async()=>{await seek('截取',.25);const v=page.locator('.preview-stage video');await expect.poll(()=>v.evaluate(v=>v.currentTime)).toBeCloseTo(original.info.duration*.25,0);await v.evaluate(v=>v.controls=false);const first=await v.screenshot();await seek('截取',.7);await page.waitForTimeout(250);const second=await v.screenshot();assert(!first.equals(second));await v.evaluate(v=>v.controls=true);await page.locator('.workspace-timeline').getByRole('button',{name:'当前位置为起点',exact:true}).click();assert((await snap()).videos[0].extractRange.start<5.25);return {seeked:true,frameChanged:true}})
 await test('裁剪播放、时间轴、时段格式及区域保存',async()=>{await operation('裁剪画面');await expect.poll(()=>page.locator('.crop-stage video').evaluate(v=>{v.muted=true;return v.readyState})).toBeGreaterThanOrEqual(2);await page.getByRole('button',{name:'裁剪播放',exact:true}).click();await expect.poll(()=>page.locator('.crop-stage video').evaluate(v=>v.currentTime)).toBeGreaterThan(.3);await page.getByRole('button',{name:'裁剪暂停',exact:true}).click();await seek('裁剪',.5);await expect.poll(()=>page.locator('.crop-stage video').evaluate(v=>v.currentTime)).toBeCloseTo(original.info.duration*.5,0);await screenshot('playable-crop-0.7.0');await time('裁剪起点','00:00.500');await time('裁剪终点','00:03.500');await page.getByRole('button',{name:'添加裁剪时段',exact:true}).click();await expect(page.getByRole('textbox',{name:'裁剪时段开始',exact:true})).toHaveValue('00:00.500');await page.getByRole('spinbutton',{name:'裁剪宽度',exact:true}).fill('360');await page.getByRole('spinbutton',{name:'裁剪宽度',exact:true}).press('Tab');await page.getByRole('button',{name:'应用裁剪区域',exact:true}).click();const crop=(await snap()).videos[0].cropSegments[0];assert.equal(crop.start,.5);assert.equal(crop.end,3.5);assert.equal(crop.rect.width,.5);return {playing:true,seeked:true,range:[.5,3.5],width:360}})
 await test('按可视范围抽帧、裁剪和查看器回归',async()=>{await page.evaluate(async(id)=>{const s=await window.framepick.snapshot();await window.framepick.chooseOutput();await window.framepick.saveSettings({...s.settings,start:1,end:3,interval:.5,includeStart:true,format:'png'});await window.framepick.setExtractRanges([id],{start:1,end:3});await window.framepick.enqueue([id])},original.id);await wait(s=>s.jobs.at(-1)?.status==='done');job=(await snap()).jobs.at(-1);const r=await page.evaluate(id=>window.framepick.results(id,0),job.id);assert.equal(r.total,4);assert(r.frames.every(f=>f.width===360));await page.getByRole('button',{name:'查看导出图片',exact:true}).click();await page.locator('.results-grid img').first().dblclick();await expect(page.locator('.image-viewer-modal')).toBeVisible();await page.keyboard.press('Control+Equal');await page.keyboard.press('Escape');await page.locator('.results-modal .ant-modal-close').click();return {frames:4,croppedWidth:360,viewer:true}})
 await test('剪切输入和模式切换可撤销',async()=>{await operation('启用视频剪切');await wait(s=>s.videos.find(v=>v.id===original.id)?.trimEnabled===true);await operation('剪切长度');await time('剪切终点','00:04.000');await page.getByRole('button',{name:'撤销时段操作',exact:true}).click();assert(Math.abs((await page.getByRole('textbox',{name:'剪切终点',exact:true}).inputValue()).split(':').reduce((sum,part)=>sum*60+Number(part),0)-original.info.duration)<.002);await page.getByLabel('删除选定时段',{exact:true}).check();await page.getByRole('button',{name:'撤销时段操作',exact:true}).click();await expect(page.getByLabel('保留选定时段',{exact:true})).toBeChecked();await page.locator('.trim-modal .ant-modal-close').click();return {timeUndo:true,modeUndo:true}})
 await test('移除中间区段并确认拼接，原视频完整',async()=>{await operation('剪切长度');await page.getByLabel('删除选定时段',{exact:true}).check();await time('剪切终点','00:04.000');await time('剪切起点','00:02.000');await screenshot('trim-video-0.7.0');await page.getByRole('button',{name:'选择位置并保存',exact:true}).click();await expect(page.getByText('是否拼接留下的视频片段？',{exact:true})).toBeVisible();await page.getByRole('button',{name:'是 · 拼接为一个视频',exact:true}).click();await wait(s=>s.jobs.at(-1)?.kind==='trim'&&s.jobs.at(-1)?.status==='done');const j=(await snap()).jobs.at(-1);joinedFile=j.outputFiles[0];const added=(await snap()).videos.find(v=>v.path===joinedFile);assert(added?.derivedFrom===original.id);assert(Math.abs(added.info.duration-(original.info.duration-2))<.15);assert.equal(hash(source),originalHash);return {joined:true,newListItem:true,duration:added.info.duration}})
 await test('选择不拼接后分段保存并加入列表',async()=>{await page.locator(`[data-video-id="${original.id}"]`).click();await operation('剪切长度');await time('剪切终点','00:02.000');await page.getByRole('button',{name:'添加时段',exact:true}).click();await time('剪切起点','00:05.000');await time('剪切终点','00:07.000');await page.getByRole('button',{name:'选择位置并保存',exact:true}).click();await page.getByRole('button',{name:'否 · 分别保存并加入列表',exact:true}).click();await wait(s=>s.jobs.at(-1)?.kind==='trim'&&s.jobs.at(-1)?.status==='done');splitFiles=(await snap()).jobs.at(-1).outputFiles;assert.equal(splitFiles.length,2);assert(splitFiles.every(f=>fs.existsSync(f)));assert((await snap()).videos.filter(v=>splitFiles.includes(v.path)).every(v=>Math.abs(v.info.duration-2)<.15));return {files:2,newListItems:true}})
 await test('所在文件夹通过系统定位接口打开',async()=>{await app.evaluate(({shell})=>{global.fpReveal=[];global.fpShow=shell.showItemInFolder;shell.showItemInFolder=file=>global.fpReveal.push(file)});await operation('所在文件夹');const shown=await app.evaluate(()=>global.fpReveal);assert.equal(shown[0],splitFiles.at(-1));await app.evaluate(({shell})=>shell.showItemInFolder=global.fpShow);return {systemFolderInterface:true}})
 await test('真实删除剪切副本，红字确认且保留原视频和记录',async()=>{await operation('删除视频文件');await expect(page.getByText('这是真正的文件删除，不是清除记录或历史。',{exact:true})).toBeVisible();const button=page.getByRole('button',{name:'真正删除 1 个文件',exact:true});await expect(button).toBeDisabled();await page.getByLabel('我已核对以上文件，确认要删除磁盘上的文件',{exact:true}).check();await button.click();await expect(button).not.toBeVisible();await expect.poll(()=>fs.existsSync(splitFiles.at(-1))).toBe(false);assert.equal(hash(source),originalHash);assert((await snap()).videos.some(v=>v.path===splitFiles.at(-1)&&v.status==='error'));return {removedFromDisk:true,sourceUnchanged:true,recordRetained:true}})
 await test('只删除所选截图，其他导出文件和记录保留',async()=>{await page.locator(`[data-video-id="${original.id}"]`).click();await page.getByRole('button',{name:'查看导出图片',exact:true}).click();const before=await page.evaluate(id=>window.framepick.results(id,0),job.id);const unrelated=path.join(job.folder,'用户其他文件.txt');fs.writeFileSync(unrelated,'preserve');await page.locator('.results-grid').getByRole('checkbox').first().check();await page.getByRole('button',{name:'删除所选图片文件',exact:true}).click();await page.getByLabel('我已核对以上文件，确认要删除磁盘上的文件',{exact:true}).check();await page.getByRole('button',{name:'真正删除 1 个文件',exact:true}).click();await expect(page.getByText('删除磁盘文件',{exact:true})).not.toBeVisible();const after=await page.evaluate(id=>window.framepick.results(id,0),job.id);assert.equal(after.total,before.total-1);assert(fs.existsSync(unrelated));assert.equal(after.missing,0);await page.locator('.results-modal .ant-modal-close').click();return {oneImageDeleted:true,unrelatedPreserved:true,resultCountUpdated:true}})
 if(url){
 await test('在线视频解析后下载到所选位置，直接播放与定位',async()=>{await page.getByRole('button',{name:'粘贴视频链接',exact:true}).click();await page.getByRole('textbox',{name:'在线视频链接',exact:true}).fill(url);await page.locator('.ant-modal:visible .ant-modal-footer .ant-btn-primary').click();await expect(page.getByRole('textbox',{name:'在线视频链接',exact:true})).not.toBeVisible({timeout:240000});await wait(s=>s.videos.some(v=>v.source==='online'&&v.localReady));online=(await snap()).videos.find(v=>v.source==='online');assert(online.downloadedPath&&!online.previewPath);await expect.poll(()=>page.locator('.preview-stage video').evaluate(v=>{v.muted=true;return v.readyState}),{timeout:60000}).toBeGreaterThanOrEqual(2);await time('截取播放位置','00:03.000');await page.getByRole('button',{name:'截取播放',exact:true}).click();await expect.poll(()=>page.locator('.preview-stage video').evaluate(v=>v.currentTime)).toBeGreaterThan(3.3);await page.getByRole('button',{name:'截取暂停',exact:true}).click();return {anonymous:true,userFolder:true,noAutoConversion:true,playing:true,seeked:true}})
 await test('明确删除下载文件，保留列表记录及本地原视频',async()=>{await operation('删除视频文件');const plan=await page.evaluate(id=>window.framepick.planDelete({videoId:id}),online.id);assert.equal(plan.files.length,1);await page.getByLabel('我已核对以上文件，确认要删除磁盘上的文件',{exact:true}).check();await page.getByRole('button',{name:'真正删除 1 个文件',exact:true}).click();await wait(s=>!s.videos.find(v=>v.id===online.id)?.mediaUrl);assert(plan.files.every(f=>!fs.existsSync(f.path)));assert.equal(hash(source),originalHash);return {downloadRemoved:true,originalUnchanged:true,recordRetained:true}})
 }
 await test('首次关闭选择托盘，隐藏后队列继续并可恢复窗口',async()=>{await page.evaluate(async id=>{const s=await window.framepick.snapshot();await window.framepick.saveSettings({...s.settings,start:0,end:5,interval:.1,includeStart:false});await window.framepick.setExtractRanges([id],{start:0,end:5});await window.framepick.enqueue([id]);await window.framepick.setCloseAction('ask')},original.id);await app.evaluate(({dialog,BrowserWindow})=>{global.fpBox=dialog.showMessageBox;global.fpAsked=false;dialog.showMessageBox=async(_w,options)=>{global.fpAsked=options.buttons.includes('隐藏到托盘');return {response:0,checkboxChecked:true}};BrowserWindow.getAllWindows()[0].close()});await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible())).toBe(false);await wait(s=>s.jobs.at(-1)?.status==='done'&&s.closeAction==='tray');assert(await app.evaluate(()=>global.fpAsked));await app.evaluate(({dialog,BrowserWindow})=>{dialog.showMessageBox=global.fpBox;const w=BrowserWindow.getAllWindows()[0];w.show();w.focus()});await expect(page.getByRole('button',{name:'设置与维护',exact:true})).toBeVisible();return {prompt:true,hidden:true,queueCompleted:true,restored:true}})
 await test('取消关闭不隐藏、重复启动恢复托盘中的窗口',async()=>{await page.evaluate(()=>window.framepick.setCloseAction('ask'));await app.evaluate(({dialog,BrowserWindow})=>{global.fpBox=dialog.showMessageBox;dialog.showMessageBox=async()=>({response:2,checkboxChecked:true});BrowserWindow.getAllWindows()[0].close()});await page.waitForTimeout(100);assert(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible()));assert.equal((await snap()).closeAction,'ask');await app.evaluate(({dialog})=>dialog.showMessageBox=global.fpBox);await page.evaluate(()=>window.framepick.setCloseAction('tray'));await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close());const child=require('node:child_process').spawn(process.env.FRAMEPICK_PACKAGED_EXE||require('electron'),process.env.FRAMEPICK_PACKAGED_EXE?['--hidden']:[root,'--hidden'],{windowsHide:true,env:{...process.env,FRAMEPICK_TEST_DATA:data,ELECTRON_RENDERER_URL:''}});const exit=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{child.kill();reject(new Error('Duplicate instance did not exit'))},15000);child.once('exit',code=>{clearTimeout(timer);resolve(code)})});assert.equal(exit,0);await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible())).toBe(true);assert.equal(hash(source),originalHash);return {cancelKeepsWindow:true,duplicateExits:true,existingRestored:true}})
 await test('托盘偏好、重启恢复及退出行为',async()=>{await app.close();app=null;await launch();assert.equal((await snap()).closeAction,'tray');await page.getByRole('button',{name:'设置与维护',exact:true}).click();await expect(page.getByLabel('关闭窗口方式',{exact:true})).toBeVisible();await screenshot('tray-settings-0.7.0');await page.getByRole('button',{name:/^完\s*成$/}).click();await page.evaluate(()=>window.framepick.setCloseAction('quit'));const closed=app.waitForEvent('close');await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close());await closed;app=null;return {remembered:true,quitExits:true}})
 await test('原视频和私人数据隔离核对',async()=>{assert.equal(hash(source),originalHash);assert.equal(errors.length,0);return {originalUnchanged:true,rendererErrors:0}})
 console.log(JSON.stringify({result:'passed',cases:cases.length,artifact}))
 }finally{report();if(app)await app.close().catch(()=>{})}})().catch(e=>{console.error(e);process.exitCode=1})
