const {_electron:electron,expect}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process')
const root=path.resolve(__dirname,'..'),version=require('../package.json').version,artifact=path.join(root,'.test-artifacts',version,'recovery-edges',String(Date.now())),data=path.join(artifact,'user-data'),output=path.join(artifact,'输出'),source=path.join(artifact,'三场景.mp4'),backup=path.join(artifact,'备份.json')
fs.mkdirSync(output,{recursive:true})
const generated=spawnSync(path.join(root,'.tools/ffmpeg.exe'),['-hide_banner','-loglevel','error','-y','-f','lavfi','-i','color=c=red:s=320x180:r=10:d=1','-f','lavfi','-i','color=c=blue:s=320x180:r=10:d=1','-f','lavfi','-i','color=c=green:s=320x180:r=10:d=1','-filter_complex','[0:v][1:v][2:v]concat=n=3:v=1:a=0[v]','-map','[v]','-c:v','libx264','-threads','2','-pix_fmt','yuv420p',source],{windowsHide:true,encoding:'utf8'});assert.equal(generated.status,0,generated.stderr)
let app,page,video,job;const cases=[],errors=[]
const snapshot=()=>page.evaluate(()=>window.framepick.snapshot()),wait=p=>expect.poll(async()=>p(await snapshot()),{timeout:60000}).toBe(true)
async function pick(file){await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},file)}
async function select(label,value){await page.getByLabel(label,{exact:true}).click();await page.locator('.ant-select-dropdown:visible').getByText(value,{exact:true}).click()}
async function configure(value){await page.evaluate(async v=>{const s=await window.framepick.snapshot();await window.framepick.saveSettings({...s.settings,...v})},value)}
async function extract(){const before=(await snapshot()).jobs.length;await page.evaluate(id=>window.framepick.enqueue([id]),video.id);await wait(s=>s.jobs.length===before+1&&!['waiting','running'].includes(s.jobs[before].status));const j=(await snapshot()).jobs[before];assert.equal(j.status,'done',j.error);return j}
async function test(name,fn){console.log('TEST '+name);const begin=Date.now();try{const details=await fn();cases.push({name,status:'passed',seconds:(Date.now()-begin)/1000,details})}catch(error){cases.push({name,status:'failed',error:error.stack});throw error}finally{fs.writeFileSync(path.join(artifact,'report.json'),JSON.stringify({version,packaged:!!process.env.FRAMEPICK_PACKAGED_EXE,cases,errors,artifact},null,2))}}
async function capture(name){const bytes=await app.evaluate(async({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0].webContents;await w.capturePage(undefined,{stayHidden:true,stayAwake:true});await new Promise(r=>setTimeout(r,150));return(await w.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG().toString('base64')});fs.writeFileSync(path.join(artifact,name+'.png'),Buffer.from(bytes,'base64'))}
;(async()=>{try{
app=await electron.launch({executablePath:process.env.FRAMEPICK_PACKAGED_EXE||require('electron'),args:process.env.FRAMEPICK_PACKAGED_EXE?['--hidden']:[root,'--hidden'],env:{...process.env,FRAMEPICK_TEST_DATA:data,ELECTRON_RENDERER_URL:'',PATH:`${process.env.SystemRoot}\\System32;${process.env.SystemRoot}`},timeout:60000});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await wait(s=>s.health.ready);await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await wait(s=>s.health.ready)
await page.evaluate(file=>window.framepick.addFiles([file]),source);await wait(s=>s.videos[0]?.status==='ready');video=(await snapshot()).videos[0];await pick(output);await page.evaluate(()=>window.framepick.chooseOutput());await configure({interval:.1,autoStitch:true,format:'png',conflict:'batch',rows:1,columns:1,thumbWidth:100,padding:4,notesEnabled:false})
await test('超过20张拼图的分页、小图和第21张独立编辑',async()=>{
 job=await extract();assert.equal(job.count,29);assert.equal(job.sheets.length,29);await page.getByRole('button',{name:'处理队列',exact:true}).click();await page.locator(`[data-job-id="${job.id}"]`).getByRole('button',{name:'查看图片',exact:true}).click();await page.getByRole('tab',{name:'拼接图 (29)',exact:true}).click();await expect(page.locator('.sheets-list figure')).toHaveCount(20);await expect.poll(()=>page.locator('.sheets-list img').first().evaluate(i=>i.complete&&i.naturalWidth<=480&&i.naturalWidth>0)).toBe(true)
 await page.getByLabel('拼接图列表分页').locator('.ant-pagination-item-2').click();await expect(page.locator('.sheets-list figure')).toHaveCount(9);await expect(page.getByRole('radio',{name:'选择第 21 张拼接图',exact:true})).toBeVisible();await page.locator('.sheets-list figure').first().getByRole('button',{name:'编辑这张',exact:true}).click();await expect(page.getByRole('tab',{name:'拼接编辑',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.locator('.story-cell[data-frame]')).toHaveAttribute('data-frame','2.1s.png');await capture('sheet-pagination');await page.locator('.results-modal .ant-modal-close').click();return {sheets:29,firstPage:20,secondPage:9,editedFrame:'2.1s.png'}
})
await test('已保存裁剪和故事板模板应用与居中比例',async()=>{
 await page.evaluate(async()=>{const s=await window.framepick.snapshot();await window.framepick.saveTemplate('裁剪 · 中心区域',{...s.settings,crop:{x:.25,y:.25,width:.5,height:.5},cropSegments:[]});await window.framepick.saveTemplate('大字模板',{...s.settings,rows:2,columns:3,noteFontSize:30,noteAlign:'center',noteColor:'#123456',notesEnabled:true})})
 await page.getByRole('button',{name:'抽帧工作台',exact:true}).click();await page.locator(`[data-video-id="${video.id}"]`).click();await page.getByRole('button',{name:'裁剪画面',exact:true}).click();await select('已保存裁剪预设','中心区域');await expect(page.getByRole('spinbutton',{name:'裁剪宽度',exact:true})).toHaveValue('160');await select('裁剪比例预设','1:1');await expect(page.getByRole('spinbutton',{name:'裁剪宽度',exact:true})).toHaveValue('180');await expect(page.getByRole('spinbutton',{name:'裁剪左边距',exact:true})).toHaveValue('70');await page.getByRole('button',{name:'恢复完整画面',exact:true}).click();await page.getByRole('button',{name:'应用裁剪区域',exact:true}).click();await wait(s=>!s.videos[0].crop)
 await page.getByRole('button',{name:'处理队列',exact:true}).click();await page.locator(`[data-job-id="${job.id}"]`).getByRole('button',{name:'查看图片',exact:true}).click();await page.getByRole('tab',{name:'拼接编辑',exact:true}).click();await select('选择故事板模板','大字模板');await expect(page.getByLabel('备注字号',{exact:true})).toHaveValue('30');await expect(page.getByLabel('拼接列数',{exact:true})).toHaveValue('3');await page.locator('.results-modal .ant-modal-close').click();return {cropPreset:true,centeredSquare:true,storyTemplate:true}
})
await test('场景抽帧与相似帧筛选的设置和真实导出',async()=>{
 await page.getByRole('button',{name:'抽帧工作台',exact:true}).click();await configure({autoStitch:false,interval:.2});await select('抽帧方式','画面变化 · 按场景抽帧');await page.getByRole('spinbutton',{name:'场景变化阈值',exact:true}).fill('5');await page.getByRole('spinbutton',{name:'场景变化阈值',exact:true}).press('Tab');await wait(s=>s.settings.sceneThreshold===5);const scenes=await extract(),sceneRecord=JSON.parse(fs.readFileSync(scenes.manifest,'utf8'));assert.deepEqual(sceneRecord.frames.map(f=>f.name),['0s.png','1s.png','2s.png'])
 await select('抽帧方式','固定时间间隔');await configure({interval:.1});await page.getByText('画面筛选与颜色',{exact:true}).click();await page.getByRole('checkbox',{name:'去除相似的连续截图',exact:true}).check();await page.getByRole('spinbutton',{name:'去重差异阈值',exact:true}).fill('1');await page.getByRole('spinbutton',{name:'去重差异阈值',exact:true}).press('Tab');await wait(s=>s.settings.deduplicate&&s.settings.similarity===1);const unique=await extract();assert.equal(unique.count,3);return {scenes:sceneRecord.frames.map(f=>f.name),deduplicated:unique.count,targets:29}
})
await test('结果移动后备份中的备注、顺序和拼接配方恢复',async()=>{
 const manifest=JSON.parse(fs.readFileSync(job.manifest,'utf8'));await page.evaluate(async({id,names})=>{const s=await window.framepick.snapshot();await window.framepick.saveStitchDraft(id,{'0.1s.png':'移动前备注，恢复后仍然保留。'},{...s.settings,rows:2,columns:2,preserveOrder:true,frameOrder:names.slice(0,4).reverse()})},{id:job.id,names:manifest.frames.map(f=>f.name)})
 await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file})},backup);await page.evaluate(()=>window.framepick.exportWorkspace());const moved=path.join(artifact,'移动后的结果');fs.renameSync(job.folder,moved);await pick(backup);await page.evaluate(()=>window.framepick.importWorkspace());const before=(await snapshot()).jobs.length;await pick(moved);await page.evaluate(()=>window.framepick.importResults());await wait(s=>s.jobs.length===before+1);const restored=(await snapshot()).jobs.at(-1),r=await page.evaluate(id=>window.framepick.results(id,0),restored.id);assert.equal(r.missing,0);assert.equal(r.notes['0.1s.png'],'移动前备注，恢复后仍然保留。');assert.deepEqual(r.stitchDraft.frameOrder,manifest.frames.slice(0,4).map(f=>f.name).reverse());assert(r.frames.every(f=>f.path.startsWith(moved)));assert(r.sheets.every(f=>f.path.startsWith(moved)));const restoredRecord=JSON.parse(fs.readFileSync(restored.manifest,'utf8'));assert.equal(Object.keys(restoredRecord.sheetRecipes).length,29);return {frames:r.total,recipes:29,notesRecovered:true,orderRecovered:true}
})
await test('损坏备份拒绝导入并保留当前工作区，结果路径越界拒绝',async()=>{
 const state=await snapshot(),bad=path.join(artifact,'损坏备份.json');const saved=JSON.parse(fs.readFileSync(backup,'utf8'));saved.workspace.jobs[0].settings.interval=0;fs.writeFileSync(bad,JSON.stringify(saved));await pick(bad);const rejected=await page.evaluate(async()=>{try{await window.framepick.importWorkspace();return false}catch{return true}});assert(rejected);assert.deepEqual(await snapshot(),state)
 const unsafe=path.join(artifact,'越界结果'),records=path.join(unsafe,'任务记录');fs.mkdirSync(records,{recursive:true});fs.writeFileSync(path.join(records,'bad.json'),JSON.stringify({frames:[{name:'0s.png',target:0,actual:0}],sheets:['C:/outside/拼接图/../../outside.png'],name:'越界记录',settings:state.settings}));await pick(unsafe);const refused=await page.evaluate(async()=>{try{await window.framepick.importResults();return false}catch(e){return e.message.includes('超出')}});assert(refused);assert.deepEqual(await snapshot(),state);assert.equal(errors.length,0);return {invalidBackupRejected:true,currentWorkspacePreserved:true,traversalRejected:true}
})
console.log(JSON.stringify({result:'passed',cases:cases.length,artifact}))
}catch(error){console.error(error);process.exitCode=1;try{await capture('failed')}catch{}}finally{if(app)await app.close()}})()
