const {_electron:electron,expect}=require('@playwright/test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path')
const root=path.resolve(__dirname,'..'),version=require('../package.json').version,artifact=path.join(root,'.test-artifacts',version,'zoom-scope',String(Date.now()));fs.mkdirSync(artifact,{recursive:true});let app
const {spawnSync}=require('node:child_process'); const sample=path.join(artifact,'generated-portrait.mp4'); const generated=spawnSync(path.join(root,'.tools/ffmpeg.exe'),['-hide_banner','-loglevel','error','-y','-f','lavfi','-i','testsrc2=duration=1:size=720x1280:rate=30','-c:v','libx264','-threads','2','-pix_fmt','yuv420p',sample],{windowsHide:true,encoding:'utf8'}); assert.equal(generated.status,0,generated.stderr)

;(async()=>{try{
app=await electron.launch({executablePath:process.env.FRAMEPICK_PACKAGED_EXE||require('electron'),args:process.env.FRAMEPICK_PACKAGED_EXE?['--hidden']:[root,'--hidden'],env:{...process.env,FRAMEPICK_TEST_DATA:path.join(artifact,'user-data'),ELECTRON_RENDERER_URL:'',PATH:`${process.env.SystemRoot}\\System32;${process.env.SystemRoot}`},timeout:60000});const page=await app.firstWindow();const ready=()=>expect.poll(()=>page.evaluate(async()=>(await window.framepick.snapshot()).health.ready),{timeout:60000}).toBe(true);await ready();await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await ready()
await page.evaluate(sample=>window.framepick.addFiles([sample]),sample);await expect.poll(()=>page.evaluate(async()=>(await window.framepick.snapshot()).videos[0]?.status),{timeout:60000}).toBe('ready');await page.getByRole('button',{name:'裁剪画面',exact:true}).click();await page.getByRole('button',{name:'100%',exact:true}).click()
const scale=()=>page.locator('.crop-stage').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).a),initial=await scale();await page.keyboard.press('Control+Shift+Equal');await expect.poll(scale).toBeGreaterThan(initial);await page.keyboard.press('Control+Minus');const first=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.getZoomFactor());assert.equal(first,1)
const box=await page.locator('.crop-preview-wrap').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.keyboard.down('Control');await page.mouse.wheel(0,-120);await page.keyboard.up('Control');await expect.poll(scale).toBeGreaterThan(initial);const second=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.getZoomFactor());assert.equal(second,1)
await page.keyboard.press('Control+Digit0');assert((await page.locator('.crop-preview-wrap').evaluate(e=>e.scrollWidth-e.clientWidth))<5);await page.keyboard.press('Escape');await expect(page.locator('.crop-modal')).not.toBeVisible();const report={result:'passed',version,packaged:!!process.env.FRAMEPICK_PACKAGED_EXE,keyboardZoomFactor:first,wheelZoomFactor:second,onlyCanvasZoomed:true,fitBounds:true,artifact};fs.writeFileSync(path.join(artifact,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report))
}finally{if(app)await app.close()}})().catch(e=>{console.error(e);process.exitCode=1})
